### ISSUE TITLE
grails 3.0.17 - Double decoding

### ISSUE THREAD

**Issue by shiranr** [grails/grails-core#10025]
Hi,

It seems there is double decoding for grails 3.0.17 when a parameter is being transferred as a path param.
For reproduction see the following project:
https://github.com/shiranr/bug
1. Run the project
2. Go to the URL: http://localhost:8080/1%2B2/view
3. In the interceptor log, you will find the line: URI: /1%2B2/view BUT PARAM IS: 1 2
For some reason, the %2B is being double decoded to space instead of staying as '+'.

Thanks,
Shiran

**Comment by liorhson** [comment]
Hey @graemerocher,

Because this issue is indeed blocker for production (Bintray [Grails 3.0.17]), we fork the **grails-web-url-mappings** project and removed the URLDecoder.decode()... line from 'AbstractUrlMappingInfo' class, line 95.

For the meantime, do you think this change can cause any other problems?

Regards,
Lior

**Comment by graemerocher** [comment]
Probably, it has been marked as a blocker for 3.1.10 and probably warrants another 3.0.x release

**Comment by ctoestreich** [comment]
@liorhson Can you elaborate how you feel the encoding issue would cause query string params to be wiped out?  Do you think it is double encoding the ? in something like ../foo/action?param=value
