### ISSUE TITLE
grails 3.1.8:Controller namespace mode, can not correctly apply colours to a render view

### ISSUE THREAD

**Issue by btboys** [grails/grails-core#10061]
Controller namespace mode, can not correctly apply colours to a render view
demo
[test 2.zip](https://github.com/grails/grails-core/files/378349/test.2.zip)

**Comment by jeffbrown** [comment]
If you move `grails-app/views/cust/index.gsp` to `grails-app/views/cust/app/index.gsp` then that view will be rendered when you send a request to http://localhost:8080/custs/app.  That behavior is described at http://docs.grails.org/3.1.8/guide/theWebLayer.html#modelsAndViews under the "Selecting Views For Namespaced Controllers" heading.

Note that your namespace is `cust` which is why the directory name is `grails-app/views/cust/` but the url contains `custs` (with an `s`) because of how you have your URL mappings configured.

**Comment by btboys** [comment]
I'm sorry, didn't describe clearly. Before the demo code is problematic. Now according to your modifications to be good.
Error scenarios are in development mode to run the code does not produce view rendering errors. An error scenario is: when put project into war in the tomcat run time, cannot normal results.


Development mode：
http://localhost:8080/custs/app
http://localhost:8080/apps/app
Is right, can get the result.

tomcat war mode(test.war):
http://localhost:8080/test/custs/app
http://localhost:8080/test/apps/app
Access the same request, will render the error.

The following is in accordance with your modified code。Not packaged in the war, is normal.
[test.zip](https://github.com/grails/grails-core/files/378534/test.zip)

**Comment by btboys** [comment]
@jeffbrown

**Comment by btboys** [comment]
@jeffbrown Project set up to now, is there a way to repair quickly? thank you

**Comment by graemerocher** [comment]
@btboys For quick, send a pull request or contract OCi support https://grails.org/support.html

Otherwise it is in the queue

**Comment by graemerocher** [comment]
I tested deploying your app to Tomcat and had no problem rendering the namespaces views
