### ISSUE TITLE
Rendering a gsp shows a blank screen if the last line of an action is setting a request attribute

### ISSUE THREAD

**Issue by selbin01** [grails/grails-core#10081]
Grails 3 rendering gsp issue, on Grails 1.37 and 2.3.11 this worked,  a link calls a controller action and that action doesn't have a render/redirect it's just setting an attribute on the  request.  This setting ends up on the results in URLMappingInfoHandlerAdapter.  The url looks correct on the return it just doesn't render the gsp which matches the action name.  Attached is an example program showing the first link is an issue that use to work and the other two show what does work. 

### Steps to Reproduce
1. run attached program
2. click on controller
3. click second link "Page B", it works, go back 
4. click third link "Page C" , it works, go back
5. click first link Page A, you will see a blank page, this is the issue, page doesn't render

Note Page A action looks like this:
  def testpageA() {
        request.pageTitle = "Page A"
    }

### Expected Behaviour
First link "Page A" should render like the other examples

### Actual Behaviour
Get a blank screen yet the url appears correct it just doesn't render.

### Environment Information
- **Operating System**: Windows
- **Grails Version:** 3.1.9
- **JDK Version:** java 8 - 1.8.0_91

### Example Application
https://github.com/selbin01/gsprendering

**Comment by jeffbrown** [comment]
I don't think setting a request attribute is really the issue.  I think the issue is that you have a controller action like this:

```
def testpageA() {
        request.pageTitle = "Page A"
}
```

As far as the return value is concerned, that is the same as doing this:

```
def testpageA() {
        "Page A"
}
```

That may have accidentally worked in old versions of Grails, but I don't think the system is designed to support that.

I think you can make it work with something like this:

```
def testpageA() {
    request.pageTitle = "Page A"
    [:]
}
```

Or:

```
def testpageA() {
    request.pageTitle = "Page A"
    render view: 'testpageA'
}
```

Or similar.

**Comment by selbin01** [comment]
I agree it's not the request causing it just the fact it's the last line in the action.  Your the expert, if you would not expect it to work this way, I'll use the workaround. 

Thanks Jeff.

**Comment by inghamfws** [comment]
We have run into this issue porting an application from Grails 2 to Grails 3.
Each time the fix is easy but we keep getting bit by in rarely encountered controller error handling code, and I wonder why it has to be this way?
If a controller action returns something Grails can't do anything with (It's extremely easy in Groovy to inadvertently return a non-null expression value), why exactly is rendering an empty page better than the rendering the action's GSP?
I hope this issue might be re-examined.
