### ISSUE TITLE
3.2.0.RC1 unable to resolve class for domain classes in application.groovy

### ISSUE THREAD

**Issue by AlexKovynev** [grails/grails-core#10131]
I have an event listener for spring security plugin as described in documentation for plugin:

grails.plugin.springsecurity.useSecurityEventListener = true

grails.plugin.springsecurity.onInteractiveAuthenticationSuccessEvent = { e, appCtx ->
   // handle InteractiveAuthenticationSuccessEvent
}

I try to import domain for do some update in event and have an error with grails startup.
In 3.1 all work fine.

**Comment by jameskleeh** [comment]
I think even if this functionality is working correctly, I would advise to put this code into it's own class unless there is a compelling reason not to. Just my 2c

**Comment by AlexKovynev** [comment]
I am already do that:) But bug is a bug, if in application.groovy we cannot use useful code, maybe drop it. .yml version is no different.

**Comment by pjdvmalan** [comment]
This seems to be an issue on 3.1.11 too.

**Comment by graemerocher** [comment]
I tested this in both 3.2 RC1 and 3.1.11 by creating a `grails-app/conf/application.groovy` file and simply doing:

```groovy
import test.*

println " test $Foo.name"
```

I have a domain class at the location `grails-app/domain/test/Foo.groovy`.

In both cases the class was found  and the name printed. So right now I cannot reproduce any issue either via `run-app` or via `java -jar` or via tomcat deployment. Please upload an example that reproduces the problem.

**Comment by AlexKovynev** [comment]
Ok, star is work for me too, but this is not:

import sklad.Foo
println " test $Foo.name"

**Comment by graemerocher** [comment]
I see, we have a decision to make then, because using Groovy code to configure the CLI (see #10075) is mutually exclusive to using Groovy code to reference application classes.

My personal opinion is that you shouldn't be able to reference application classes directly in `application.groovy` and this is working as designed. /cc @jameskleeh

**Comment by jameskleeh** [comment]
@graemerocher Perhaps this type of config could be in a different `.groovy` file that would only be loaded in the runtime ?

**Comment by rlovtangen** [comment]
Ran into this issue because I'm using an enum in my config, which I think is reasonable:
````
import grails.plugin.springsecurity.SecurityConfigType
...
grails.plugin.springsecurity.securityConfigType = SecurityConfigType.InterceptUrlMap
````
Has been working in all Grails versions from 2.0.0 up to 3.1.10, but fails in 3.1.11

Using FQN works:
````
grails.plugin.springsecurity.securityConfigType = grails.plugin.springsecurity.SecurityConfigType.InterceptUrlMap
````

**Comment by graemerocher** [comment]
The reason for this issue is the fix for #9899

Some folks want to use only `application.groovy` and not have to use `application.yml`.

Problem is the CLI has to be able to load `application.groovy` without the project's classes being compiled. Hence the complication error.

The possible solutions are:

1) Revert the fix for #9899 and document that only `application.yml` can be used to configure the command line

or 

2) Keep the fix for #9899 but add an additional configuration file for configuration that references application classes (example `application-runtime.groovy`

I personally think 1) is unfortunately the way to go, although some people don't like the YAML as 2) complicates configuration further. Thoughts welcome.

**Comment by rlovtangen** [comment]
Agree that going back to 1) is unfortunate.
With the current workarounds (using star import or using FQN), I'm fine with the current behaviour as long as it is documented.

**Comment by virtualdogbert** [comment]
I'm not a fan of yml, and I don't use it, but after looking at #9899 I can see where you are coming from. While 2 does make it so that you have another file, I'm not opposed to that.  In fact I liked having my db config in a separate file(like Grails 2), which I sure I could figure out how to do.  It would be a little work to port to having two separate files, but it wouldn't be the end of the world. as long as they would be two separate groovy files :)

Also it would be nice if it wasn't called application, because you have application.groovy for config and Application.groovy to run the app.

**Comment by rlovtangen** [comment]
I would love to see something similar as the BootStrap support for multiple files, where you can have `MyBootStrap.groovy`, `MyOtherBootstrap.groovy` etc in addition to `BootStrap.groovy` and they will all get executed.
Would be nice to be able to split configuration up in multiple files. Makes it also easier to have a non version controlled config file to override properties pr developer.

And +1 for calling it something other than `application.groovy`. `config.groovy` for instance.

**Comment by AlexKovynev** [comment]
Maybe you apply fix to 3.2 branch too?

**Comment by jameskleeh** [comment]
@AlexKovynev Branches get merged up 3.1.x -> 3.2.x -> master

**Comment by edwardotis** [comment]
+1 for option 2. 
I parse several config urls from environment variables  in the Heroku addon style for redis, jdbc, rabbitmq, etc. I have to parse the username and/or password out of these urls for use in the respective grails config.  This is not possible with yaml.
In addition, I was using my own helper utilities to do some of this parsing in Grails 2.x for Config.groovy.
It worked quite well. If grails goes pure yml, it will be more difficult configure my applications.

**Comment by graemerocher** [comment]
You can use `grails-app/conf/runtime.groovy` for this

**Comment by edwardotis** [comment]
Thanks, and for Grails 3.1.x,  I would need to revert to 3.1.10 or earlier?

**Comment by graemerocher** [comment]
No the changes were included in 3.1.12 so you should upgrade to 3.1.14

**Comment by edwardotis** [comment]
gotcha, thanks

**Comment by mlim1972** [comment]
I started a migration from Grails 2.5.4 to Grails 3.3.1 and I'm encountering this issue.  Did the fix make it to 3.3.1?

> script1507230323134407332247.groovy: 6: unable to resolve class grails.util.Holders
>  @ line 6, column 1.
>    import grails.util.Holders
>    ^
>

**Comment by jameskleeh** [comment]
@mlim1972 Yes. As Graeme said above, use `runtime.groovy`

**Comment by rlovtangen** [comment]
With regards to `runtime.groovy`. I mentioned runtime.groovy to a colleague the other day, and tried to find some documentation for it. As far as I can see it is not mentioned in the documentation for 3.3 (http://docs.grails.org/3.3.0/guide/single.html). 
It is mentioned under "3.2 Upgrading from Grails 3.0" and "3.1 Upgrading from Grails 3.1" in the documentation for 3.2 (http://docs.grails.org/3.2.0/guide/single.html), but that part is not included in the latest doc.
Should maybe be mentioned under "4.1 Basic Configuration"?

**Comment by jameskleeh** [comment]
@rlovtangen Sure, PRs welcome

**Comment by abcfy2** [comment]
Thanks. I'm wondering why `gradle assemble/bootrun/check` works very well, but `grails run-app/war/test-app` gives me `script15362435064771376469692.groovy: 1: unable to resolve class` error.

This issue asked my question.
