### ISSUE TITLE
Add (back) support for external java domains

### ISSUE THREAD

**Issue by davidklebanoff** [grails/grails-core#10181]
It is my understanding that support for external Java domains that use JPA annotations and hibernate configurations has silently been removed from GORM 5+ (and thus Grails 3.1+). I unfortunately discovered this a day into upgrading our 2.5.x Grails application to the latest version of Grails 3.

I, as I imagine many others as well, use Grails as the web component of an existing Java infrastructure - one that uses Hibernate and JPA annotations. Duplicating our current models into GORM's groovy format simply doesn't make sense, and I encourage Grails/GORM to make continued use of the existing Java standards (JPA) as they did before. Unfortunately the lack of support in the latest versions of Grails/GORM leaves me unable to upgrade.

This issue is to serve as a request to add back support for the feature. 👍 

References to the feature in the current documentation (I guess these are currently incorrect?):
http://docs.grails.org/3.1.11/guide/hibernate.html
http://docs.grails.org/3.1.11/ref/Command%20Line/create-hibernate-cfg-xml.html

If I have missed anything, I apologize, as I could not find any official information regarding dropped JPA support - only slight mentions in some other closed issues.

**Comment by graemerocher** [comment]
It isn't technically possibly to add back this feature, since GORM was rewritten to use compile time AST transformations and all metaprogramming logic removed.

This has several advantages (better performance, easier to debug, less memory consumption) but unfortunately means that java domains aren't supported.

It *may* be possible to implement some kind of bridge by creating a dynamically compiled subclass for each java domain, although I'm not sure how that can be done, and again re-introduces meta programming and memory consuming metaprogramming features.

**Comment by davidklebanoff** [comment]
Understood. Quite the pickle. As a backup, I suppose one could use plain Hibernate instead of GORM, but you would obviously lose some of the core advantages of Grails.

**Comment by jameskleeh** [comment]
GORM 6.1 will include support for JPA annotations on Groovy classes. There are no plans to extend that support to Java classes.

**Comment by davidklebanoff** [comment]
@jameskleeh , @graemerocher 

A nice step in the right direction! Any words to why this wouldn't automatically work with Java  classes as well?

**Comment by jameskleeh** [comment]
@davidklebanoff Because the support relies on Groovy AST transformations
