### ISSUE TITLE
Geb Specs not honoring server.contextPath

### ISSUE THREAD

**Issue by scrain** [grails/grails-core#10306]
Integration tests launch the browser with an empty context root when `server.contextPath` is configured causing tests to not work.

Grails 3.1.x

Looks to be due to how `geb.base.url` is being populated in `IntegrationTestMixinTransformation`

https://github.com/grails/grails-core/blob/master/grails-plugin-testing/src/main/groovy/org/grails/compiler/injection/test/IntegrationTestMixinTransformation.groovy#L177

**Comment by jeffbrown** [comment]
I have rigged up the AST transformation so that it considers `server.contextPath` when setting `geb.build.baseUrl`.  However, I am still seeing a problem.

The issue relates to https://github.com/geb/geb/blob/fa05c94f114ffdff4c74f6348ff6e7c11cbd3d95/module/geb-core/src/main/groovy/geb/Browser.groovy#L965 which calls the following:

`uri = new URI(getBaseUrlRequired()).resolve(uri)` 

If `getBaseUrlRequired()` evaluates to something like `http://localhost:58615/abc` and `uri` evaluates to something like `/def` then `new URI(getBaseUrlRequired()).resolve(uri)` evaluates to `http://localhost:58615/def` so the context path is being dropped.

```
groovy:000> new URI('http://localhost:58615/abc').resolve('/def')
===> http://localhost:58615/def
```

**Comment by jeffbrown** [comment]
It looks like the Geb part of this is behaving as documented:

http://www.gebish.org/manual/current/#base-url

I will investigate but it looks like we might be able to improve things by appending a trailing `/` to the base url that the AST transformation is generating.  I will conduct some tests and report back.

**Comment by jeffbrown** [comment]
With the AST transformation change that I made at https://github.com/grails/grails-core/commit/4fac5bfd4fa7ca47c0e33674b3cde00be066fe52 then it appears to be the case that if `server.contextPath` is set in `application.yml` (or similar) to something like `/abc/` and a `GebSpec` issues a command like `go 'def'` then the request will be sent to `http://localhost:<port number>/abc/def`.

**Comment by jeffbrown** [comment]
The AST transformation could be made to append the trailing `/` to the base url if it isn't already there but it would still be up to the test to specify a relative path like `go 'xyz'`, not `go '/xyz'`.
