### ISSUE TITLE
Sometimes Content-Type header missing

### ISSUE THREAD

**Issue by demon101** [grails/grails-core#10394]
Sometimes Content-Type header missing for template without layout. 

### Steps to Reproduce

1. action return template without layout (**render (template:'/test/template', model:[....])**)
2. check contentType response header in browser 

### Expected Behaviour

`Content-Type:text/html;charset=UTF-8` header presented in all html responses 

### Actual Behaviour

Sometimes Content-Type header missing for views without layout.  For some tires of same page loading -- it's missing. One time per 10-100 tries  

The bug was fixed by changing render template to view (without layout). 

### Environment Information

In application.yml default config presented

> views:
>         gsp:
>             encoding: UTF-8

Grails version 3.1.14

**Comment by graemerocher** [comment]
We have an ISSUE_TEMPLATE for a reason, please follow it and provide all of the requested information including a sample application that reproduces the issue.

See https://github.com/grails/grails-core/blob/master/ISSUE_TEMPLATE.md

**Comment by davidkron** [comment]
I had exactly the same issue recently and had to do some intense debugging to find the source of the problem. In my case, the problem was caused by the mail plugin's HTML rendering. I opened an issue in their tracker: https://github.com/grails3-plugins/mail/issues/23

I don't know if you managed to solve the problem yourself, but maybe this can help others facing the same problem. I created the following class as a workaround, which extends the one from the mail plugin to fix the issue:
https://github.com/davidkron/mail-plugin-renderissue/blob/master/src/main/groovy/grails/plugins/mail/renderissue/MailMessageContentRenderer.groovy

To use it, you have to register it in resources.groovy:
```
mailMessageContentRenderer(MailMessageContentRenderer) {
    it.autowire = true
}
```

**Comment by demon101** [comment]
@davidkron big thx for the information. The bug fix still important to me. 
I already understood bug caused by some of plugins. But I could not imagine, mail plugin is guilty =)
