### ISSUE TITLE
constraints insertable: false, updateable: false not working as before

### ISSUE THREAD

**Issue by R-Mark** [grails/grails-core#10421]
I have an integration test that I am porting from a previous Grails 2.3.11 project into a Grails 3.2.4 rest-api-plugin.  But this integration test breaks in the new environment.  It involves saving a new entity where the relationship to the parent (belongsTo) is also constrained as insertable: false, updatable: false. We don't expect any save/update of the child to have to save the parent, just at a minimum save the foreign key reference. In our situation, this is not working as the logged SQL for the parent id column ends up being null. We have confirmed in our test setup that the parent is a persisted reference, i.e. it has an id. If we change the insertable constraint to true, it works. This is counter to how our Grails 2.3.11 app has been working.

Attaching sample project that reproduces the issue.

[insert-update-constraint.zip](https://github.com/grails/grails-core/files/724451/insert-update-constraint.zip)

**Comment by graemerocher** [comment]
Try move `, insertable: false, updateable: false` to the `mapping` block instead. Since these are not constraints

**Comment by R-Mark** [comment]
Yes, that makes sense.  Did what you suggested in our plugin and to the sample project I have attached.  Still receiving the same results.  Do you want me to re-attach the changes to the sample?  The integration test is OrderIntegrationSpec.

**Comment by graemerocher** [comment]
Will take a look.. thanks

**Comment by graemerocher** [comment]
Maybe I am missing something but I am unsure this is a bug, insertable and updatable are generally for the case where you want to use the same column and read multiple properties from the same column whilst only having one property actually update the column (whilst the rest are `updatable` and `insertable` false).

From the sound of your requirements it seems like what you really want is `cascade: 'none'` which ensures no updates are cascaded to the parent entity.

As to why it was working before, I am unsure of that, maybe we were not passing `updatable` and `insertable` configuration correctly and now are. I don't understand how it can possibly work otherwise because something has to populate the `stock_id` column to create the foreign key reference and with `insertable` and `updatable` in place that is happening.

**Comment by R-Mark** [comment]
So perhaps I misunderstand your own documentation:
http://docs.grails.org/latest/ref/Database%20Mapping/insertable.html

Which seems to support my use case.  But your suggestion of cascade: 'none' is essentially what I am trying to achieve.  The mapping is not bidirectional, ie no hasMany from the parent.  So I would have assumed cascade: 'none' would have been by default.

The other thing I noted was the following:
http://stackoverflow.com/questions/3805584/please-explain-about-insertable-false-updatable-false
where the first reply indicates usage is to indicate the child is not responsible for updating the parent.  Which is kinda consistent with your documentation.  But I'm beginning to think that is wrong since that should really be under the control of cascade.

Yea, I can see what you are saying.  I'll try cascade: 'none'

Thanks
