### ISSUE TITLE
Upgrade to Groovy 2.4.8

### ISSUE THREAD

**Issue by 2point718** [grails/grails-core#10423]
Please see if Grails 3.2.5 can use Groovy 2.4.8 now that it is available. Groovy 2.4.8 has some major fixes related to memory leaks (http://groovy-lang.org/changelogs/changelog-2.4.8.html)

**Comment by AlexKovynev** [comment]
Maybe don't hurry?:)
https://github.com/spring-projects/spring-boot/commit/daf6be46f64b09a5daa7c8c26c28725acfbfddae
https://issues.apache.org/jira/browse/GROOVY-8065

**Comment by graemerocher** [comment]
Other than that the current test failures are due to `final` being broken with traits. The `Interceptor` trait uses `final`, and all final fields are `null`: https://github.com/grails/grails-core/blob/master/grails-plugin-interceptors/src/main/groovy/grails/artefact/Interceptor.groovy#L63

This is causing the current test failures.

**Comment by graemerocher** [comment]
We are waiting for 2.4.9

**Comment by jeffbrown** [comment]
#10502
