### ISSUE TITLE
Grails 3.2.4 <g:include> merges controller params when includes are nested

### ISSUE THREAD

**Issue by christophmegusta** [grails/grails-core#10424]
i already filed it on Stackoverflow as question as we werent sure if its a bug or a feature.
http://stackoverflow.com/questions/41704307/why-does-grails-merge-nested-ginclude-tag-params-into-a-single-list
Its confusing if i copy the same g:include line with same parameters to another gsp and get different results. Even if there is a reasonable reason for this, it should be clearly documented.

### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. create a index.gsp with a <g:include controller="outer" action="list" params="[page:11]">
2. create outer controller with action list and a list.gsp view another <g:include controller="inner" action="list" params="[page:22]">. also printout params.page its a single value.
3. create inner controller and display or printout params.page . its a list containing [22,11].

### Expected Behaviour

params.page should always be a single value or the value it was given in the include.
OR
its documented in grails doc

### Actual Behaviour

params.page is a merged list of all values instead

### Environment Information

Tested on Grails 3.2.4, current MacOS and Ubuntu Linux.

### Example Application

git clone https://github.com/aistomin/includes-bug.git
grails run-app
open http://localhost:8080
watch console output

### Workaround

Gladly there is a easy workaround. Use params.list('page')[0] instead of params.page. As the first value in the list seams always be the correct one for that controller. Its also working in case page is no list on highest level.

**Comment by demon101** [comment]
@christophmegusta I had same problem.
Somewhere here I read that this is expected behavior of servlets include logic

**Comment by kdpeders** [comment]
This seems like a bug.  I can see where issue #9526  was closed as won't fix with the argument that forwarding should be in the same context and therefore use the same params.  g:include on that other hand is used to include a separate full page in the current view, and the only way to properly specify the controller/action based page is via the params object (which could reasonably have different values than the current page).

**Comment by kdpeders** [comment]
I can see this issue has been open for 6 months w/o any comments/assignee.  I can also see where @christophmegusta provides a possible workaround.  However, that workaround requires the list to always be in the same order.  Could someone from the Grails team comment on whether this is a valid assumption/workaround?

**Comment by danduke** [comment]
Concur that this seems like a bug.  The workaround does not account for the fact that the presence of a param may in itself mean something.  <g:include> should allow full control over what parameters are provided to the action.  If the original parameters are needed, perhaps they could be passed along in a map called "originalRequest.params" or similar.

**Comment by christophmegusta** [comment]
@kdpeders 

    params.list('page')[0]

the array is the same order. basically its the reversed nesting index.
value where 0 == is the least nesting / or the value from the previous g:include,
therefore you can confidently use index [0] if you handle the case that list('page') might not be a array or null.

**Comment by benrhine** [comment]
As stated above referencing #9526 this is expected behavior. With that said I think I see some of the confusion around this so to elaborate a bit. 

When making a web request that has a `g:include` in the path even though you are loading another page it does not make a seperate request, it is all encapsulated in the parent request. You can see this by opening the chrome debugger and that even with multiple nested `g:include`'s there is only ever a single request present. 

Internally the urls are created the way that is expected and you end up with something like `/inner/list?page=2+size=10` but the params available durring include execution are seperate from the actual request params which is what is available when the page renders. So if you have multiple nested pages all of which use the same variable names by the time the page renders you have a list in the request params.

If you wish to avoid the parameter concatination and ensure the example displays correctly, give the parameters unique names like the following example (make sure to updated other associated values)

`<g:include controller="outer" action="list" params="[page:1,size:5]"/>`
`<g:include controller="inner" action="list" params="[innerPage:2, innerSize:10]"/>`
`<g:include controller="deepest" action="list" params="[deepestPage:3, deepestSize:20]"/>`

![screen shot 2018-05-07 at 12 51 56 pm](https://user-images.githubusercontent.com/2130719/39713728-cfdd26b4-51f5-11e8-8c81-b6c294e0f219.png)

**Comment by aistomin** [comment]
@benrhine sorry, but you explain why it is _working_ like that, but not why it is _designed_ like that. What is the idea behind this "include" mechanism? To me it always looked like I can _inject_ some smaller pieces and compose some complex page. This including, in my understanding, assumes some encapsulation, but, according to what you say above, this encapsulation is ruined. ```DeepestController.list()``` must always be aware of the parameters names which are used in the upper context. It, basically, closely ties all the pieces together and makes it impossible to modify them separately.
