### ISSUE TITLE
CORS configuration does not work in Grails 3.2.8

### ISSUE THREAD

**Issue by pawelhalasa** [grails/grails-core#10584]
### Steps to Reproduce

1. Create a new app
`grails create-app myapp`
2. Enable CORS in application.yml (as described in [Grails docs](http://docs.grails.org/latest/guide/theWebLayer.html#cors))
   ```YAML
   grails:
       cors:
           enabled: true
   ```
3. Run the app
4. Open the website in web browser, inspect network traffic and check server response headers

### Expected Behaviour

The following headers should be included in HTTP responses:
```HTTP
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
```

### Actual Behaviour

Expected headers are not included in HTTP responses

### Environment Information

- **Operating System**: Windows 7
- **Grails Version:** 3.2.8
- **JDK Version:** 1.8

### Example Application

[myapp.zip](https://github.com/grails/grails-core/files/921691/myapp.zip)

**Comment by jameskleeh** [comment]
This is by design. The headers will only be returned for CORS requests.

**Comment by trav010** [comment]
> This is by design. The headers will only be returned for CORS requests.

If that behavior is by design, what exactly do you mean with "only for CORS requests" and how should we handle the following situation?

I observed that `OPTIONS` requests get a server response with those `Access-Control-Allow-...` headers, while e.g. `POST` requests do not get responses with the required `Access-Control-Allow-...` headers. That results in error messages like the following:
`Access to fetch at '<https://sub1.your-domain.org/api/resources'> from origin '<https://sub2.your-domain.org'>
has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`
What would you suggest to do to avoid such errors? Adding the missing headers in a proxy server (instead of the server app) seems to be a very odd solution. Am I missing something?
