### ISSUE TITLE
isDirty() and getPersistentValue(..) should work the same as hasChanged() and getOriginalValue()

### ISSUE THREAD

**Issue by demon101** [grails/grails-core#10609]
- [X] Steps to reproduce provided
- [X] Example that reproduces the problem
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1. Update domain by properties
2. check changed fields by isDirty (return false) and getPersistentValue (return some trash)

### Expected Behaviour

Dirty checking mast work same with direct assignment (isDirty return true for changed field )

### Actual Behaviour
 isDirty -- return false for changed field,  getPersistentValue return some trash

### Environment Information

- **Grails Version:** 3.2.9
gormVersion=6.0.10.RELEASE

### Example Application

https://github.com/demon101/grails-example-10585

```
class TestDomain {
    String name

    static constraints = {
    }

    def beforeValidate(){
        log.error "${name}: beforeValidate isDirty:${isDirty('name')}"
    }

    def beforeUpdate () {
        log.error "${name}: beforeValidate isDirty:${isDirty('name')}, ${getPersistentValue('name')}"
    }
}
```

```
        log.error "Create new"
        def d = new TestDomain(name: "Old Name").save(flush:true, failOnError:true)
        d.refresh()



        log.error "Update name: "
        d.name = "new name"
        d.save(flush:true, failOnError:true)

        d.refresh()

        log.error "Update by properties: "
        d.properties = [name: "new name 1"]
        d.save(flush:true, failOnError:true)

        d.refresh()

        log.error "Update by bindData: "
        bindData(d, [name: "new name 2"])
        d.save(flush:true, failOnError:true)
```

>: Create new
>: Old Name: beforeValidate isDirty:false
>: Update name: 
> : new name: beforeValidate isDirty:true
> : new name: beforeValidate isDirty:true, Old Name
> : Update by properties: 
> : new name 1: beforeValidate isDirty:false
> : new name 1: beforeValidate isDirty:false, 1
> : Update by bindData: 
> : new name 2: beforeValidate isDirty:false
> : new name 2: beforeValidate isDirty:false, 2

At last two lines -- wrong result of isDirty = false and  getPersistentValue -- return "1"

**Comment by demon101** [comment]
For bindData -- same problem

**Comment by graemerocher** [comment]
The issue is that dirty checking has been re-written to use our dirty checking implementation via the `DirtyCheckable` interface, but the methods `getPersistentValue` and `isDirty` still use the old Hibernate API.

Replacing their usage with `hasChanged(..)` and `getOriginalValue` fixes the example:

```groovy
 log.error "${name}: beforeValidate isDirty:${hasChanged('name')}, ${getOriginalValue('name')}"
```

The fix to get `getPersistentValue` and `isDirty` working again is to remove the overridden implementations defined here: https://github.com/grails/gorm-hibernate5/blob/master/grails-datastore-gorm-hibernate5/src/main/groovy/org/grails/orm/hibernate/HibernateGormInstanceApi.groovy#L66

When this is done we should also deprecate `getPersistentValue` and `isDirty`

As I said, however, the issue is not that serious as simply using `hasChanged(..)` and `getOriginalValue` can be used as a workaround.

**Comment by demon101** [comment]
@graemerocher  I hope, this kind of information about broken changes will become part of release notes in the future. 
By the way, is it possible to write suggested GORM version in Grails release notes? For example in https://github.com/grails/grails-core/releases/tag/v3.2.9 only written:

> gormVersion=6.1.2
But in newly created Grails 3.2.9 application contain

> gormVersion=6.0.10.RELEASE

**Comment by graemerocher** [comment]
If we had known about the change we would have written about it, as is the case here, we were not aware the impact of the change and hence didn't document. Nevertheless there is a workaround available, so you're in luck.

As for the GORM version, it is currently `6.0.10.RELEASE` because we never upgrade to a new major release of a dependency in a patch release. But GORM 6.1 is out and stable so we encourage people to try it.

**Comment by demon101** [comment]
@graemerocher 
hasChanged() works well, but getOriginalValue in my case return null. Will prepare example 


> As for the GORM version, it is currently 6.0.10.RELEASE because we never upgrade to a new major release of a dependency in a patch release. But GORM 6.1 is out and stable so we encourage people to try it.

I understand grails dependency upgrade strategy, I only tell, information about gorm version should be added to release notes like you have written about asset-pipeline
`runtime "com.bertramlabs.plugins:asset-pipeline-grails:2.14.1" `

**Comment by demon101** [comment]
@graemerocher  example app has for **getOriginalValue()** bug been added https://github.com/demon101/grails-example-10585

**Comment by demon101** [comment]
@graemerocher  please, remove tags No Example Attached & Workaround Available & Minor
New method getOriginalValue() not working

**Comment by graemerocher** [comment]
No need to remove either Workaround Available or Minor because a work around does exist, which is to revert to hibernate dirty checking:

```yaml
hibernate:
    hibernateDirtyChecking: true
```

In addition, upgrading to GORM 6.1.2 in the application also resolves the issue of `getOriginalValue` returning `null`, so you have a secondary workaround without adding the above configuration since that particular issue is unique to GORM 6.0.x.

Finally your example is not valid because it is missing calls to `d.discard()` between each update to the object, otherwise you are modifying the same object over and over and only the original value is considered the value.

**Comment by demon101** [comment]
@graemerocher after simple upgrade to  to GORM 6.1.2 I get error for some plugin Domain class

> Execution failed for task ':compileGroovy'.
> Unable to load class com.rate.Rating due to missing dependency org/grails/datastore/gorm/async/GormAsyncStaticApi

The plugin was built with grails 3.1.3.
Is it usual behavior, described in doc or I should create an issue?

I hope workaround with hibernateDirtyChecking will become a part of Grails 3.2.9 release notes

**Comment by graemerocher** [comment]
add the `grails-datastore-gorm-async` dependency or recompile the plugin

**Comment by demon101** [comment]
I didn't test too much, but with:

```
hibernate:
    hibernateDirtyChecking: true
```

```
grailsVersion=3.2.9
gormVersion=6.0.10.RELEASE
```
and with d.properties=params, isDirty() not working well

**Comment by demon101** [comment]
@graemerocher 
I have fixed the example app

1.  dirty checking totaly brocken, not only for update by properties or bindData()
2. isDirty() & getPersistentValue() stop working after insertion of beforeInsert() with any content (same with #10609) 
3. `hibernate.hibernateDirtyChecking = true` don't fix the bug with isDirty() & getPersistentValue()
4. getOriginalValue method works with GORM 6.1.2 only

**Comment by demon101** [comment]
@graemerocher Ha ha,

With GORM 6.1.2 got error in my application for domain which implements a trait =) 

> Caused by: org.hibernate.PropertyNotFoundException: Could not locate field name [finished] on class [xxx.EditInfo]
> 	at org.hibernate.internal.util.ReflectHelper.findField(ReflectHelper.java:356)
> 	at org.hibernate.property.access.internal.PropertyAccessFieldImpl.<init>(PropertyAccessFieldImpl.java:34)
> 	at org.hibernate.property.access.internal.PropertyAccessStrategyFieldImpl.buildPropertyAccess(PropertyAccessStrategyFieldImpl.java:26)
> 	at org.hibernate.mapping.Property.getGetter(Property.java:308)
> 	at org.hibernate.tuple.entity.PojoEntityTuplizer.buildPropertyGetter(PojoEntityTuplizer.java:257)
> 	at org.hibernate.tuple.entity.AbstractEntityTuplizer.<init>(AbstractEntityTuplizer.java:147)
> 	at org.hibernate.tuple.entity.PojoEntityTuplizer.<init>(PojoEntityTuplizer.java:60)
> 	at org.grails.orm.hibernate.proxy.GroovyAwarePojoEntityTuplizer.<init>

Will create an issue for GORM.

**Comment by graemerocher** [comment]
Seems I was confused. We only introduced a custom dirty checking implementation in GORM 6.1.x the class https://github.com/grails/grails-data-mapping/blob/master/grails-datastore-gorm-hibernate-core/src/main/groovy/org/grails/orm/hibernate/dirty/GrailsEntityDirtinessStrategy.groovy

Doesn't exist on the 6.0.x branch. So the `hibernate.hibernateDirtyChecking = true` setting actually has no effect whatsoever in 6.0.x

So the issue is something else which we are investigating

**Comment by demon101** [comment]
Same problem in grails 3.2.10 and Gorm 6.0.10. getOriginalValue('field') return null, getPersistentValue('field') retrun some trash, sometimes it current time. But hasChanged() and isDirty() now working well!!!
With GORM 6.0.11 getPersistentValue works well,  getOriginalValue returns null

@graemerocher  What version of GORM you recommend to use with Grails 3.2.10?

**Comment by MichaelMorett** [comment]
@demon101 Thanks for bringing this issue up.  I'm on Grails 3.2.9 and Gorm 6.0.10.RELEASE like you were originally.  

Making no changes or applying no workarounds, I see this (inside a constraint custom validator):

obj.hasChanged("department") = true
obj.isDirty("department") = false

As Joe Biden would say, this is a BFD.  

That validation code is unfortunately triggered by a Show method, by data binding/phase 1 validations.  The only reason I'm having to use hasChanged()/isDirty() is because of those phase 1 validations.  There's something very uncomfortable about "retrieve some data and display it on a page"....and having it validated without your consent.  If I wanted to validate it, I would validate it.  instance.validate() is available for me.  Instead, it's validated without my consent.  

So now, I have a constraint needs to be aware of 3 distinct possibilities:
--adding a record
--editing a record (specifically that value)
--a show() method (or really any data binding which opens it up to many possibilities)

It's those last two items that caused me to stumble on this bug report. 

I can distinguish between adding and editing by virtue of examining obj.id.

I now need to add some isDirty checking that won't invert the results on me should I decide to update to a later version of GORM and/or fail to apply the workaround mentioned here.  I searched for that workaround (i.e. hibernateDirtyChecking: true) -- the Grails docs didn't mention it and the GORM docs didn't mention it.  The best documentation of it is....(drumroll)....this bug report.

**Comment by graemerocher** [comment]
The problem is fixed by this commit https://github.com/grails/grails-data-mapping/commit/01fc32cb496516cb98326348aa3294fc69c8d2ec which is present in GORM 6.0.11, so you will need to upgrade by setting your `gormVersion` in `gradle.properties`

**Comment by demon101** [comment]
@graemerocher 

> With GORM 6.0.11 getPersistentValue works well, getOriginalValue returns null
