### ISSUE TITLE
Unable to access VM options in grails command context

### ISSUE THREAD

**Issue by dshrestha** [grails/grails-core#10706]
### Steps to Reproduce

1. grails create-app test-app
2. grails create-command test

 ```java
    //TestCommand.groovy 
    boolean handle() {
        println(System.getProperty("OPTION-1"))
        return true
    }
```

3. grails run-command test -DOPTION-1=TEST

### Expected Behaviour

should have printed **TEST**

### Actual Behaviour

prints **null**

### Environment Information

- **Grails Version: 3.3.0RC1
- **JDK Version:1.8

Currently I can access the arguments using getArgs(). But I am unable to leverage gorm for mongodb where I would pass in connection parameters from VM option rather than hard code them in application.yml

**Comment by danduke** [comment]
I stumbled across this while looking through existing issues, and figured I would give you some pointers as a workaround while waiting for the experts to weigh in.

For normal system properties and run-app, you can prefix them with "grails." and they'll be passed along automatically.  This appears to not be true for run-command.  That may be intentional?  I'm not sure.

You can do something like this in your build.gradle, but I'd consider this a risky starting point and improve it from here!

    runCommand { runTask ->
        configure(runTask) {
            systemProperties System.properties
        }
    }

This will give run-command EVERY system property you have (which is what you say you want), and that isn't especially safe.  You may end up with more than you wanted.  Prefixing with "grails." is definitely safer, so you might want to alter the example to only use the properties that are prefixed.  Or, only pass in known and expected properties, based on your environment.

Hopefully the grails team can update the run-command task to look for prefixed properties by default, because it seems like it would be nice for it to be consistent with what run-app does.

**Comment by dshrestha** [comment]
@danduke thanks for the answer, I just added the script that you provided for build.gradle and I was able to get to the config values. Thanks a lot again.
