### ISSUE TITLE
Odd behavior with hardcoded variables and defining the request method

### ISSUE THREAD

**Issue by chris13524** [grails/grails-core#10855]
It looks to me that in order to define [arbitrary variables](http://docs.grails.org/latest/guide/theWebLayer.html#_arbitrary_variables), you cannot set the method before the endpoint.

So for example, if you were to define the URL mapping like this:
```
"/two"(controller: "bob", action: "two") {
    method = "GET"
    arbitrary = "data"
}
```
Inside the controller, `params.arbitrary` would be equal to "data" as expected.

However, if you were to define the URL mapping like this instead:
```
get "/one"(controller: "bob", action: "one") {
    arbitrary = "data"
}
```
Inside the controller, `params.arbitrary` is null.

### Steps to Reproduce

1. Enter /two in your browser, you will get a `[:]` printed.
2. Enter /one in your browser, you will get a `[controller:bob, method:GET, arbitrary:data, action:two]` printed.

### Expected Behaviour

In both cases, the arbitrary variable data should be available in the params object.

### Actual Behaviour

The arbitrary variable data is only available when using `method = "GET"`.

### Environment Information

- **Operating System**: Ubuntu 17.10
- **Grails Version:** 3.2.11
- **JDK Version:** 1.8.0_151

### Example Application

[grails-test.zip](https://github.com/grails/grails-core/files/1464349/grails-test.zip)

**Comment by chris13524** [comment]
I just discovered that arbitrary variables will now only work for one request type. In the below example, all requests for `/two` will be sent to the second action, regardless of method:
```
"/two"(controller: "bob", action: "get") {
    method = "GET"
    arbitrary = "data"
}
"/two"(controller: "bob", action: "post") {
    method = "POST"
    arbitrary = "data"
}
```
This means that if you want to use arbitrary variables, you can't use multiple request types.

**Comment by ilopmar** [comment]
Thanks for submitting the issue @chris13524 

I've created the following Grails 3.3.2 project with different ways to define url mappings.

As you can see here:
https://github.com/grails-core-issues-forks/grails-issue-10855/blob/master/grails-app/controllers/issue10855/UrlMappings.groovy#L5-L49

Defining the `method` as an arbitrary parameter is not working. Actually according to the documentation http://docs.grails.org/3.2.2/guide/theWebLayer.html#mappingHTTP the only way to map http method seems to be using `method` as a "namedParameter" instead an "arbitrary variable".
But, on the other hand, I think it is actually a bug because defining the mappings as in `/seven` doesn't work.

**Comment by chris13524** [comment]
Thanks, I sort of guessed that `method = "GET"` didn't actually do anything... But thanks for the fix!
