### ISSUE TITLE
Grails 3.3.x angular profile domain creation

### ISSUE THREAD

**Issue by ValoData** [grails/grails-core#10850]
Thanks for reporting an issue for Grails framework, please review the task list below before submitting the 
issue. Your issue report will be closed if the issue is incomplete and the below tasks not completed.

NOTE: If you are unsure about something and the issue is more of a question a better place to ask questions is on Stack Overflow (http://stackoverflow.com/tags/grails) or Slack (http://slack-signup.grails.org). DO NOT use the issue tracker to ask questions.

### Task List

- [ ]  Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [ ] Full description of the issue provided (see below)

### Steps to Reproduce

1.  create an app with the Angular profile
$grails create-app --profile angular -features hibernate5,json-views todo
2. create an angular domain
~/todo/server/$ grails create-ng-domain todo

### Expected Behaviour

| Rendered template NgControllerSpec.js to destination src/test/javascripts/todo/controllers/todoControllerSpec.js
| Rendered template NgController.js to destination grails-app/assets/javascripts/todo/controllers/todoController.js

### Actual Behaviour

| Error Command not found create-ng-domain

### Environment Information

- **Operating System**: Linux Mint 18.2
- **Grails Version:** 3.3.0
- **JDK Version:** 1.8
- **Container Version (If Applicable):** TODO

### Example Application

- TODO: link to github repository with example that reproduces the issue

**Comment by jameskleeh** [comment]
@ValoData The commands are not part of the angular profile

http://docs.grails.org/latest/guide/REST.html#angularProfile

"The Angular profile is designed to be used with the Angular CLI. The CLI was used to create the client application side of the profile to start with. The CLI provides commands to do most of the things you would want to do with the client application, including creating components or services. Because of that, the profile itself provides no commands to do those same things."

**Comment by jameskleeh** [comment]
In case you are not aware of the name changes of the angular profiles:  http://grailsblog.objectcomputing.com/posts/2017/04/12/angular-profiles.html

The angular profile in Grails 3.2.9+ is for Angular 2.x+
The angularjs profile in Grails 3.2.9+ is for Angular 1.x
