### ISSUE TITLE
[Issue]: Databinding array items from json request

### ISSUE THREAD

**Issue by tkvw** [grails/grails-core#10909]
Example project (core branch): 
https://github.com/tkvw/issue-java8-localtime/tree/core

This fails because the collection is not cleared when a new array is assigned. Not sure if this is by design, but if so; how can I remove an entity from the array?  

Issue split off from https://github.com/grails/grails-data-mapping/issues/1053

**Comment by tkvw** [comment]
Any news on this issue? I can take a look myself, but like to have it confirmed that this is an issue.

**Comment by sdelamo** [comment]
A workaround is to to set: ` items(cascade: "all-delete-orphan")`

That is to say:
```
import grails.rest.Resource

@Resource(uri="/timeTables")
class TimeTable {
    boolean inactive
    String name
    
    static hasMany = [items:TimeTableItem]
    static constraints = {
    }
    static mapping = {
        items(cascade: "all-delete-orphan")
    }
}

```

**Comment by tkvw** [comment]
I can confirm the workaround works, thanks!

**Comment by sdelamo** [comment]
You have two possibilities to replace a many-to-one collection

Given these GORM entities:

```
class Book {
    String name
    static hasMany = [reviews: Review]
}
class Review {
    String author
    String quote
    static belongsTo = [book: Book]
}
```

## A) A clear the old reviews yourself.

You could create a method to replace the `reviews` collection as illustrated next:

```
Book replaceReviews(Serializable idParam, List<Review> newReviews) {
    Book book = Book.where { id == idParam }.join('reviews').get()
    clearReviews(book)
    newReviews.each { book.addToReviews(it) }
    book.save()
}

void clearReviews(Book book) {
    List<Serializable> ids = []
    book.reviews.collect().each {
        book.removeFromReviews(it)
        ids << it.id
    }
    Review.executeUpdate("delete Review r where r.id in :ids", [ids: ids])
}
```

## B) Leverage cascade behaviour 

Alternatively, you could leverage [cascade behaviour](http://docs.grails.org/latest/ref/Database%20Mapping/cascade.html).

```
class Book {
    String name
    static hasMany = [reviews: Review]
    static mappping = {
        reviews cascade: 'all-delete-orphan'
    }
}
class Review {
    String author
    String quote
    static belongsTo = [book: Book]
}
```

The cascade behaviour takes cares of deleting every orphan `Review`. Thus, invoking `.clear()` suffices to remove the book' previous reviews.

```
Book replaceReviews(Serializable idParam, List<Review> newReviews) {
    Book book = Book.where { id == idParam }.join('reviews').get()
    book.reviews.clear()
    newReviews.each { book.addToReviews(it) }
    book.save()
}
```

# Conclusion

Grails binds automatically the JSON Payload to a many-to-one collection and it class `.clear()`. Thus, you could add the cascade constraint to your domain class as mentioned before to get the behavior you want. 

However,  we cannot change the binder to do the `deleteFrom` automatically because it will load the association lazily and thus hurt performance in a binding such as the one you describe; replace all elements in a collection. That it is to say, if you don't want to use the cascading behaviour you will need to create your own endpoint which calls a method in a service which does the replacement efficiently as illustrated above. 

I will close this issue. @tkvw thanks for submitting
