### ISSUE TITLE
Change gradleWrapperVersion

### ISSUE THREAD

**Issue by tkvw** [grails/grails-core#10941]
If I change the `gradleWrapperVersion` property in `gradle.properties` and execute `./gradlew wrapper` the wrapper is not updated to the expected version. Is this expected behaviour? 

Workaround: 
`./gradlew wrapper --gradle-version=4.5`  or specifying a `wrapper` task in `build.gradle`: 
```
wrapper{
   gradleVersion=$gradleWrapperVersion
}
```
I expect the latter to be added by the `grails-gradle-plugin`. 
If this is expected behaviour I should probably PR for a note in the docs.

**Comment by jeffbrown** [comment]
Is the behavior you are seeing in a Grails app any different than what you see in a non Grails app using the same version of Gradle?

Thanks for the feedback.

**Comment by jeffbrown** [comment]
@tkvw I still don't understand.  Is the behavior you are seeing in a Grails app any different than what you see in a non Grails app using the same version of Gradle?  Are you saying the answer to that is "yes"?  Thanks again for your feedback.

**Comment by tkvw** [comment]
No, the behaviour is exactly the same. I just expected that grails would have a `preconfigured` `wrapper` task in the `grails-gradle-plugin`. Otherwise what's the use of the `gradleWrapperVersion` in `gradle.properties`?

**Comment by benrhine** [comment]
This is expected behaviour as this is Gradle functionality not Grails. You can review all the gradle wrapper doc [here](https://docs.gradle.org/current/userguide/gradle_wrapper.html) but for a quick answer the `gradle wrapper` command by itself is for generating the initial wrapper file and it defaults to whatever version of gradle is installed. Thus if you are trying to run with `./gradlew wrapper` it will default to the version of the wrapper you are alredy using.

As for upgrading the wrapper, what you are specifying as a workaround is actually the documented upgrade path for the gradle wrapper found [here](https://docs.gradle.org/current/userguide/gradle_wrapper.html#sec:upgrading_wrapper). 

Concerning the `grails-gradle-plugin` this is for providing the connecting glue between gradle and grails commands. Take a look at the doc [here](https://github.com/grails/grails-gradle-plugin), but a quick example is it maps `./gradlew clean` to `grails clean`. Which since the wrapper task is gradle specific it wouldnt really make sense to add it to the plugin.

If you want to override the default wrapper task you can do so as 
```
wrapper{
    gradleVersion="$gradleWrapperVersion"
}
```
 if you want to make specific use of the value in `gradle.properties`, but which option is more convenient (the task override vs documented wrapper upgrade) is up to your discretion and project based needs.
