### ISSUE TITLE
Grails 3.3.3 integration tests no longer works with Gradle 4

### ISSUE THREAD

**Issue by erichelgeson** [grails/grails-core#10959]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a fresh grails 3.3.3 app
2. Update it to Gradle 4
3. Run integration tests
`./gradlew integrationTest` || `./gradlew check`

### Expected Behaviour

Integration tests should run.

### Actual Behaviour

Test fail instantly - it seems the app doesn't try to start before failing with:
```
java.lang.IllegalStateException: No GORM implementations configured. Ensure GORM has been initialized correctly
	at org.grails.datastore.gorm.GormEnhancer.findSingleDatastore(GormEnhancer.groovy:380)
	at org.grails.datastore.gorm.GormEnhancer.findSingleTransactionManager(GormEnhancer.groovy:399)
	at gradle4.PortSpec.setup(PortSpec.groovy)
```

### Environment Information

- **Operating System**: Mac 10.13.3
- **Grails Version:** 3.3.3
- **JDK Version:** 8u151
- **Container Version (If Applicable):** n/a

### Example Application

- https://github.com/erichelgeson/issueGrails333Gradle46/commit/92623a4ea0572427ca2f03c4eaf2359a8a2fb03e

NOTE: We were using gradle 4 in our Grails 3.3.2 project without issue.

**Comment by tlefevre** [comment]
It seems that Grails 3.3.3 doesn't even attempt to start the tomcat server in integrationTest. 

Grails 3.3.3 with Gradle 4.6.

**Comment by mortensoby** [comment]
the compileGmlViews-task doesn't work with gradle 4.6 either. It can't resolve imports in the GMLs. This might be related.

**Comment by bkoehm** [comment]
I see that the milestone has been set to grails-3.3.6, but in the meantime could anyone in the know explain a little about what's causing this?  I'm in the middle of trying to upgrade plugins from 3.2.x to 3.3.x and I'm running into this on one of my plugins.  My first suspicion was that I didn't have the right dependencies listed, but perhaps it's more than that.  Just looking for some insight to try and judge if I can fix this on my own plugin before 3.3.6 comes out.  Thanks.

**Comment by bkoehm** [comment]
For me, the problem was that Hibernate dependencies were required.  If you do "grails create-app test-app" with 3.3.4, you'll see:
    compile "org.grails.plugins:hibernate5"
    compile "org.hibernate:hibernate-core:5.1.5.Final"

Adding that into my build.gradle fixed the issue for me.
(You *may* need some of the other dependencies too in build.gradle from "grails create-app test-app".  Not sure.)

It used to be that Hibernate wasn't required for tests, but that no longer seems to be the case.

 

    On Friday, April 27, 2018, 6:24:21 AM PDT, Kadambari87 <notifications@github.com> wrote:  
 
 
Hi,

I have upgraded my application to grails 3.3.5 and I am using gradle wrapper version 4.6. However,the integration tests are failing. The error I get is - " Caused by:
org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.xms.core.candidateFeed.ReedGlobalPostingService]: Constructor threw exception; nested exception is org.springframework.dao.DataAccessResourceFailureException: Could not obtain current Hibernate Session; nested exception is org.hibernate.HibernateException: No Session found for current thread"

I have marked the test cases as @transactional. Is there any other configuration that is required? I am using spock and grails testing to create the integration tests. Below is a sample of how I have created the test case:

@integration
@Rollback
class X extends Y {
def setupSpec () { }
def cleanSpec () { }

@transactional
def "testcase1"() {
///// test case here
}
}
Below are defined in my build.gradle

testCompile "org.grails:grails-gorm-testing-support"
testCompile "org.grails:grails-plugin-testing"
testCompile "org.grails:grails-web-testing-support"
testCompile "org.grails:grails-plugin-testing"
testCompile "org.grails.plugins:geb"

**Comment by bkoehm** [comment]
Update: I got this exception again in unit tests even after adding the hibernate dependencies.  Turns out adding "implements DataTest" to the unit test solves it.
CC @Kadambari87

**Comment by ppazos** [comment]
I'm getting this exception in Grails 3.3.9 from a plugin that actually doesn't need GORM, and I need to create an integration test, not sure how to proceed. This happens when the integration test runs.

```
java.lang.IllegalStateException: No GORM implementations configured. Ensure GORM has been initialized correctly
	at org.grails.datastore.gorm.GormEnhancer.findSingleDatastore(GormEnhancer.groovy:383)
	at org.grails.datastore.gorm.GormEnhancer.findSingleTransactionManager(GormEnhancer.groovy:402)
	at com.cabolabs.security.stateless.TestPluginSpec.setup(TestPluginSpec.groovy)
```

**Comment by niravassar** [comment]
I would try a few things:

- Use @Integration annotation along with extending `Specification`
- Try connecting the test environment to the h2 run time database 
- create a real domain object and see how it behaves

**Comment by ppazos** [comment]
My "plugin that actually doesn't need GORM", so no H2 connections and no domain classes here.

**Comment by chrisbuttaro** [comment]
Thanks niravassar "Use @Integration" worked for me.

**Comment by amcegan** [comment]
@ppazos 
I realise it has been a long time since you had this issue but can you remember if you got it sorted. I have the same configuration (Grails 3.3.9) as you and am having the same issue. Thanks.

**Comment by ppazos** [comment]
@amcegan I just run a test and got the same issue again, now on a project that uses GORM

I have the hibernate deps for compile and tested adding them as testCompile, but got the same result.

This is on a test that was autogenerated when I ran grails create-service BalanceUpdate, and this is the class header generated:

`class BalanceUpdateServiceSpec extends Specification implements ServiceUnitTest<BalanceUpdateService>`

When I run the test:

```
java.lang.IllegalStateException: Either class [com.cabolabs.security.Team] is not a domain class or GORM has not been initialized correctly or has already been shutdown. Ensure GORM is loaded and configured correctly before calling any methods on a GORM entity.
	at org.grails.datastore.gorm.GormEnhancer.stateException(GormEnhancer.groovy:467)
	at org.grails.datastore.gorm.GormEnhancer.findStaticApi(GormEnhancer.groovy:298)
	at org.grails.datastore.gorm.GormEnhancer.findStaticApi(GormEnhancer.groovy:294)
	at org.grails.datastore.gorm.GormEntity$Trait$Helper.currentGormStaticApi(GormEntity.groovy:1368)
	at org.grails.datastore.gorm.GormEntity$Trait$Helper.getGormPersistentEntity(GormEntity.groovy:424)
	at org.grails.datastore.gorm.GormEntity$Trait$Helper.addTo(GormEntity.groovy:337)
	at com.cabolabs.cloud.BalanceUpdateServiceSpec.setup_closure3(BalanceUpdateServiceSpec.groovy:182)
	at groovy.lang.Closure.call(Closure.java:420)
	at com.cabolabs.cloud.BalanceUpdateServiceSpec.setup(BalanceUpdateServiceSpec.groovy:180)
```

**Comment by DarwisNarvaezDev** [comment]
Using @Integration worked for me, thanks!
