### ISSUE TITLE
Why 3.3.9 version did miss some commits from master?

### ISSUE THREAD

**Issue by pelenthium** [grails/grails-core#11185]
Hi guys, we are waiting 3.3.9 with some fixes but now, as I can see some commits from masters did miss
as an example - fixes for #11054 from 25-26 Aug
list all of the missed commits - https://github.com/grails/grails-core/compare/v3.3.9...master

**Comment by ilopmar** [comment]
Hi @pelenthium. The issue #11054 was fixed in PR #11080 that was submitted again Grails `master` branch. We have released Grails 3.3.9 based on the changes in `3.3.x` branch. That's why that fix is not included in the released.
We haven't missed those commits you link, they belong to `master` branch and will be included in Grails 4.0.0.

**Comment by pelenthium** [comment]
@ilopmar Thanks! Do you have a plan to release 3.3.10? if yes,  may be we need to make PR to 3.3.x branch?

**Comment by ilopmar** [comment]
We have just released 3.3.9 so releasing a new version is not in our schedule at this moment. If your changes don't introduce a breaking change (apparently they did but I'm not 100% sure), feel free to submit a new PR against 3.3.x branch and link the issue and the original PR.
