### ISSUE TITLE
request parameters contain map (like: a[b]=c) cause Exception

### ISSUE THREAD

**Issue by vgrails** [grails/grails-core#11200]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create an demoController and index action
2. Create an normal request, past an parameter like http://127.0.0.1:8080/demo/index?a[b]=c
### Expected Behaviour
recieve the params["a[b]"]=c
### Actual Behaviour
Server can't parse the parameter normal and throw an exception

Tell us what happens instead

### Environment Information

- **Operating System**: WIN/Linux
- **Grails Version:** 3.3.8
- **JDK Version:** 1.8.152
- **Browser:** Chrome

**Comment by ddelponte** [comment]
I am no expert on the related RFC, but I don't think `a[b]=c` is a valid use of parameters.

The answer to this stackoverflow question breaks down the RFC nicely:  https://stackoverflow.com/questions/11490326/is-array-syntax-using-square-brackets-in-url-query-strings-valid

**Comment by bobbywarner** [comment]
You actually can use the map syntax in databinding with Grails and it works as expected.  The reason this example doesn't work is because the characters need to be encoded.

For instance, you can successfully post data like this:
```
a%5Bb%5D=c
```
This particular syntax is typically used with databinding collections.
