### ISSUE TITLE
Not able to generate SSL certificate with Java 8, Grails 2.4.4 and Tomcat 7.0.55

### ISSUE THREAD

**Issue by gagandeepchhabda12305** [grails/grails-core#11206]
Hi All,

I need to generate an SSL certificate for my Grails application and I am facing the following issue:
|Creating SSL Certificate...
Error |
Exception in thread "main"
Error |
java.lang.ClassNotFoundException: com.ibm.crypto.tools.KeyTool

I am using Java 8, Grails 2.4.4 and Tomcat 7.0.55 and I tried the fix suggested for replacing the code of TomcatServer.groovy but it didn't work for me, can someone please help me in the same.

Thanks

**Comment by smakela** [comment]
That KeyTool class is moved to another package in java 8. So quick "fix" would be to run with java 7.
Or you can try first just run and create that ssl stuff with java 7 and then run it with java 8.

**Comment by smakela** [comment]
I tested it and you can just once run int with java 7 "grails run-app -https" and create the certificate. After that you can run it with java 8.

**Comment by smakela** [comment]
The real problem is that the class name is wrong for the 7.x version of the tomcat plugin.

`Class.forName 'sun.security.tools.KeyTool.Main`

it should be:

`Class.forName 'sun.security.tools.keytool.Main`

7.x version of the plugin has this typo in the class name and it was never released as 7.x version.

If you want this to work you should do:

1. Update the tomcat plugin at least to version 8.0.18.3
https://github.com/grails-plugins/grails-tomcat-plugin/pull/12/files/1acab7cfdf518ad32c71ea5ee3e977acc26f9f79#diff-822df8609ef3795deab01f39bad6476e

2. If you want to use the 7.x version of the plugin just patch the TomcatServer.groovy by yourself.

3. Use the hacks that i mentioned above.

@graemerocher I this can be closed, because fix already exists.
