### ISSUE TITLE
Grails 4: Spring DevTools breaks DI of Micronaut beans

### ISSUE THREAD

**Issue by graemerocher** [grails/grails-core#11287]
When DevTools is active Micronaut's bean classes are loaded by a different classloader to the devtools classloader. This causes a failure to find Micronaut end user beans.

**Comment by niravassar** [comment]
I have created a sample project that reproduces the problem

It is a grails 4 app created with the default web profile. 

https://github.com/niravassar/grails-micronaut-bean

**NOTES**

- I needed to add compileOnly "io.micronaut:micronaut-inject-groovy" in order to get the bean definition created at compileTime. This is not in the webprofile. I assumed this would already be there, but I had to poke around and add it. Should this is a precursor and possibly part of this fix?
- when I removed the devTools, then grails finds the micronaut bean defined with `@Singleton`. The BeanController will get the injected bean and use it
- When I add back the devTools dependency grails cannot find the bean
- If you run the app as a bundled jar with `gradlew assemble`, then `java -jar build\libs\grails-micronaut-bean-0.1.jar`, the bean is found and method can be executed.

**Comment by niravassar** [comment]
**Debugging*

- in GrailsApp, I looked into how the applicationContexts are put together. The spring context placed the micronaut as its parent.
- when devTools is not listed as a dependency, micronaut beans are accessible and are able to be injected into the app.  `applicationContextBuilder.classPathResourceLoader` has `AppClassLoader` in it from rt.jar java. This works with the grails 4 ap when there are micronaut beans
- when the devTools is used as a dependency  `applicationContextBuilder.classPathResourceLoader` now has `RestartClassLoader` which is a devTools class. I suspect this is a reason why the beans are not part of the context.

**TRIED*

- i tried two small things which did not work
1) just removed line :136 from `GrailApp`.
2) made :136 this: ` applicationContextBuilder.classLoader(applicationContext.getClassLoader())`. I did this to see if the context in the session is different from the `RestartClassLoader`. It is not. Its the same, so we get the same error

```
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'grails.micronaut.bean.PrintMe' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1654)
```

Obviously the devTools is intercepting the classLoader process somewhere, and we need to find out how to get the original class loader back when devTools is activated. Looking for some assistance.
