### ISSUE TITLE
JSONObject does not support BigInteger and BigDecimal value.

### ISSUE THREAD

**Issue by abcfy2** [grails/grails-core#11327]
Here is my question from stackoverflow: https://stackoverflow.com/questions/56160624/how-to-handle-post-a-biginteger-in-jsonobject-in-grails-controller

And I find the reason is that `JSONObject` only support number format `Long`, `Integer` and `Double`, without `BigDecimal` and `BigInteger`.

https://github.com/grails/grails-core/blob/de270aedbef5a1af1a11e25554847c0f953682f8/grails-web-common/src/main/groovy/org/grails/web/json/JSONTokener.java#L389-L420

### Task List

- [ ] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [ ] Full description of the issue provided (see below)

### Steps to Reproduce

see: https://stackoverflow.com/questions/56160624/how-to-handle-post-a-biginteger-in-jsonobject-in-grails-controller

### Expected Behaviour

`JSONObject` could support `BigInteger` and `BigDecimal` value.

### Actual Behaviour

`BigInteger` will be conver to `Double`, and caused arithmetic overflow. 

### Environment Information

- **Operating System**: Linuxmint 19.1
- **Grails Version:** 3.3.6
- **JDK Version:** 1.8
- **Container Version (If Applicable):** TODO

**Comment by niravassar** [comment]
@jameskleeh or @jeffbrown or @graemerocher 

I looked this over and tested. 

I tested this in in 3.3.9 and recreated the problem. I then proceeded to create a patch locally and tested the PR. It rusn correctly on a sample app and returns BigInteger and BigDecimal when the number is very large (exceeds long and double limitations).  The solution in the PR code progressively returns an Integer, long, or BigInteger when there are no decimals. In the decimals case, it progressively returns a Double or a BigDecimal.

Whether this goes into the Grails web-common depends on interpretation of the following:

https://tools.ietf.org/html/rfc7159#page-6 (snippet below)	

```
  This specification allows implementations to set limits on the range
   and precision of numbers accepted.  Since software that implements
   IEEE 754-2008 binary64 (double precision) numbers [IEEE754] is
   generally available and widely used, good interoperability can be
   achieved by implementations that expect no more precision or range
   than these provide, in the sense that implementations will
   approximate JSON numbers within the expected precision.  A JSON
   number such as 1E400 or 3.141592653589793238462643383279 may indicate
   potential interoperability problems, since it suggests that the
   software that created it expects receiving software to have greater
   capabilities for numeric magnitude and precision than is widely
   available.
 ```
 
My interpretation is that it is saying that if you are sending big numbers (more than double precision according to iEEE754), then you should expect interoperability problems because you are expecting the server to have greater than normal capabilities. If  I am correct, then it would mean this PR wouldn't be accepted because currently we support double precision and that is normal. 
 
However, java does provide BigInteger and BigDecimal which is more accommodating. If that is valuable to users, then grails could accept the PR with no harm.

**Comment by abcfy2** [comment]
Close this issue due to #11350
