### ISSUE TITLE
Grails 4.0.0.RC2 -  Compile issue with profile "plugin" and`grails create-service` command 

### ISSUE THREAD

**Issue by puneetbehl** [grails/grails-core#11342]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a new Grails plugin. (`grails create-app example.myplugin --profile=plugin`.
2. Create a new service via command `grails create-service example.BookService`
3. Execute `./gradlew compileGroovy`.

### Expected Behaviour

Project should compile successfully.

### Actual Behaviour
```
> Task :compileGroovy FAILED
startup failed:
/private/tmp/plugin/grails-app/services/demo/BookService.groovy: 3: unable to resolve class grails.gorm.transactions.Transactional
 @ line 3, column 1.
   import grails.gorm.transactions.Transactional
   ^

1 error
```

### Environment Information

- **Operating System**: macOS Mojave (Version 10.14.5)
- **Grails Version:** 4.0.0.RC2
- **JDK Version:** 1.8
- **Container Version (If Applicable):** N/A

### Example Project

See https://travis-ci.org/grails-profiles-tests/plugin/builds/543070082

**Comment by ZacharyKlein** [comment]
The issue here is that the `base` profile provides `create-service` command, which uses a template that in turn imports `grails.gorm.transactions.Transactional`. However, the `base` profile doesn't require the `hibernate5` feature which brings in the required GORM dependency for that import to work. This doesn't seem to be an issue with the `plugin` profile per se, except that this profile doesn't include the GORM dependency (which makes sense - not every plugin needs GORM), which causes this issue to pop up. 

@jameskleeh I'm not sure if the solution is to remove the `create-service` command from `base`, or remove the `@Transactional` from the `Service.groovy` template, or make `hibernate5` a required dependency. Thoughts?

**Comment by jameskleeh** [comment]
@ZacharyKlein Most likely only make it so create-service is available from the profiles where a gorm implementation is provided by default

**Comment by ZacharyKlein** [comment]
Remove `create-service` command and templates from `base` and added it to `web` and `rest-api` - the two profiles that include the `hibernate5` feature as default.

- https://github.com/grails-profiles/base/pull/30
- https://github.com/grails-profiles/web/pull/18
- https://github.com/grails-profiles/rest-api/pull/10
