### ISSUE TITLE
Micronaut Primary bean not recognised as Primary in Grails 4

### ISSUE THREAD

**Issue by erichelgeson** [grails/grails-core#11367]
# Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Use a mn bean in a grails service that has 2 qualifying beans (in this case [lettuce](https://micronaut-projects.github.io/micronaut-redis/latest/guide/))

### Expected Behaviour

The bean marked as Primary should be used.

### Actual Behaviour

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Field statefulRedisConnection in grails.ExampleService required a single bean, but 2 were found:
	- io.lettuce.core.api.StatefulRedisConnection(Primary): defined in null
	- io.lettuce.core.pubsub.StatefulRedisPubSubConnection($DefaultRedisClientFactory$RedisPubSubConnectionDefinition): defined in null

Action:

Consider marking one of the beans as @Primary, updating the consumer to accept multiple beans, or using @Qualifier to identify the bean that should be consumed
```

### Work around

Add qualifier
```
@Qualifier("io.lettuce.core.api.StatefulRedisConnection(Primary)")
```

### Environment Information

- **Operating System**: macOs 10.14.5
- **Grails Version:** 4.0.0
- **JDK Version:** 11.0.2
- **Container Version (If Applicable):** n/a

### Example Application

- https://github.com/erichelgeson/mnbeansPrimary/commit/0a35af50193bb6e4764ad449fc1b2e77c1fa0ea1

**Comment by andersaaberg** [comment]
@jameskleeh : I upgraded the example project (https://github.com/erichelgeson/mnbeansPrimary/commit/0a35af50193bb6e4764ad449fc1b2e77c1fa0ea1) to Grails 4.0.1 (https://github.com/andersaaberg/mnbeansPrimary/commit/3396fa6f8d6cf5227f0ba8cce85bf52d86b39534), but it still fails on startup with the error:
`
Caused by: org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type 'io.lettuce.core.api.StatefulRedisConnection<?, ?>' available: expected single matching bean but found 2: io.lettuce.core.pubsub.StatefulRedisPubSubConnection($DefaultRedisClientFactory$RedisPubSubConnectionDefinition),io.lettuce.core.api.StatefulRedisConnection(Primary)
`

**Comment by jameskleeh** [comment]
@andersaaberg I have added tests for this in `grails3-functional-tests`. Ensure you have `micronaut-spring:1.0.2` on your classpath

**Comment by andersaaberg** [comment]
@jameskleeh I have extended your test with injection of an actual StatefulRedisConnection bean: https://github.com/grails/grails3-functional-tests/pull/22

The test only passes when using the qualifier as workaround: @Qualifier("io.lettuce.core.api.StatefulRedisConnection(Primary)")

Am I doing something wrong?

**Comment by jameskleeh** [comment]
@andersaaberg Hard to say. You can debug https://github.com/micronaut-projects/micronaut-spring/blob/a4f1bd7618ec4c8d1c298777adf881fa0ef65120/spring-context/src/main/java/io/micronaut/spring/context/factory/MicronautBeanFactory.java#L804 to see if the bean is getting correctly identified as primary
