### ISSUE TITLE
After changing from grails version 2.5.6 to 3.3.9 Internationalization is not working. 

### ISSUE THREAD

**Issue by anuragrxlogix** [grails/grails-core#11410]
If I have given the input as 薬協ラインリスト(準テンプレート)

then the output saved in the Database is given below
è¬åã©ã¤ã³ãªã¹ã(æ¨æºãã³ãã¬ã¼ã)

But When we save the English alphabet, then this is working fine

### Environment Information

- **Operating System**: Ubuntu 18.04
- **Grails Version:** 3.3.9
- **JDK Version:** 1.8
- **Container Version (If Applicable):** TODO

**Comment by jameskleeh** [comment]
Please provide an example application that reproduces the issue

**Comment by jeffbrown** [comment]
@anuragrxlogix Can you provide a sample project with a failing test that will help us understand what the issue is?

**Comment by davydotcom** [comment]
This is likely due to a bad jdbc connection string. One can set the default character set on the connection string to UTF8 such that this works perfectly in grails 3 and 4:

Example jdbc url:

```
            url = "jdbc:mysql://127.0.0.1/morpheus_development?useTimezone=true&serverTimezone=GMT&useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&maxReconnects=10"
```

Pay special attention to `useUnicode` as well as `characterEncoding`. This application is also running grails 3.3.9 and confirmed functioning correctly with Chinese (Simplified) characters

**Comment by bobbywarner** [comment]
As per @davydotcom 's comment, this works as expected.

If you still encounter issues, please provide a sample app that demonstrates the problem.
