### ISSUE TITLE
Provide option to use spring-loaded (on java8) instead of dev-tools

### ISSUE THREAD

**Issue by erichelgeson** [grails/grails-core#11439]
On large applications spring dev-tools "fast restart" is not a workable solution as restarts can take up to 3 minutes for each change.

Provide a way for developers to choose their dev-reload feature (eg spring-loaded, dev-tools, or none). 

Note spring-loaded does work once these two commits were reverted on master -https://github.com/grails/grails-core/commit/d9a422d13209308688610a120fa4b5a612dad017 & a2772f81c810275a6c317a7545018d068f22ce01

Note this only works on Java 8.

**Comment by dularion** [comment]
Seconded, this causes big issues for for larger applications, which is one of the reasons that we have  not yet upgraded all applications to grails4. 
Also, it spams the log very heavily for each change: 

![image](https://user-images.githubusercontent.com/936076/69714046-f8820280-1105-11ea-92a3-117d4a06dd01.png)

**Comment by davidkron** [comment]
@erichelgeson Do you have any experience or suggestions for optimizing an existing Grails 4 application for better startup performance? Are there other workflows (besides JRebel) that make Grails 4 development faster?

Since we plan to do a full framework and runtime upgrade soon, we would not want to stay on JDK 8, so this re-enabling of spring-loaded would not work for newer JDKs.

**Comment by erichelgeson** [comment]
@davidkron 2 major things - make sure you don't accidentally have a class in the "default package" - this will cause scanning of every class in your app. Second is to skip things on fast restart with a flag in bootstrap (eg, we dont need to re-seed data or each fast restart) - I'll have a PR for a flag for that too soon. Unfortunately this still leaves our app at 1+ min restarts. Jrebel or SpringLoaded are really the only way to get back to what grails was.
