### ISSUE TITLE
Using @Value('${config.vaue}') it is impossible to override value in test if it's defined in application.<yml|groovy>

### ISSUE THREAD

**Issue by demus-nine** [grails/grails-core#11651]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Annotate a property with @Value('${features.someFeatureToEnable:false}')
2. Add a key to application.yml -> features.someFeatureToEnable: true
3. Write a unit test that sets config.features.someFeatureToEnable = false in fx. doWithConfig

### Expected Behaviour

Annotated property should have the value set to false in doWithConfig {}.

### Actual Behaviour
Annotated property always has the value true as set in application.yml.

### Environment Information

- **Operating System**: Fedora 33
- **Grails Version:** 4.0.4
- **JDK Version:** 11.0.9

### Example Application

- TODO: link to github repository with example that reproduces the issue

This method in org.springframework:spring-core 5.x.x:
```	@Nullable
	protected <T> T getProperty(String key, Class<T> targetValueType, boolean resolveNestedPlaceholders) {
		if (this.propertySources != null) {
			for (PropertySource<?> propertySource : this.propertySources) {
				if (logger.isTraceEnabled()) {
					logger.trace("Searching for key '" + key + "' in PropertySource '" +
							propertySource.getName() + "'");
				}
				Object value = propertySource.getProperty(key);
				if (value != null) {
					if (resolveNestedPlaceholders && value instanceof String) {
						value = resolveNestedPlaceholders((String) value);
					}
					logKeyFound(key, propertySource, value);
					return convertValueIfNecessary(value, targetValueType);
				}
			}
		}
		if (logger.isTraceEnabled()) {
			logger.trace("Could not find key '" + key + "' in any property source");
		}
		return null;
	}
```

Looks for the key in the @Value annotation in each propertySource. application.yml and application.groovy precede grailsApplication.config in the list and the search returns the first hit. If the key is set in application.yml it will always return that value, irrespective of doWithConfig. grailsApplication.config should replace application.yml and application.groovy in the list, or be moved before them.

**Comment by puneetbehl** [comment]
The problem is happening because of a bug in Micronaut for Spring where:
1. The parentBeanFactory is not set for MicronautApplicationContext.
2. The [MicronautBeanFactory](https://github.com/micronaut-projects/micronaut-spring/blob/master/spring-context/src/main/java/io/micronaut/spring/context/factory/MicronautBeanFactory.java) does not even check the parent. Check the following method implementation:  
[`doGetBean(String name, Class<T> requiredType, Object[] args, boolean typeCheckOnly)`](https://github.com/micronaut-projects/micronaut-spring/blob/master/spring-context/src/main/java/io/micronaut/spring/context/factory/MicronautBeanFactory.java#L669)

I am working on fixing the same in Micronaut for Spring.
