### ISSUE TITLE
I suggest inserting in the section whatsNew Support Environments Concept in Micronaut Context

### ISSUE THREAD

**Issue by fernando88to** [grails/grails-core#13078]
### Feature description

I suggest inserting in the grails 6.0.0 documentation section whatsNew Support Environments Concept in Micronaut Context

**Comment by puneetbehl** [comment]
That's is a good suggestion. I also believe it should be included in the documentation. Would you interested to contribute to the Grails Documentation, otherwise I will do it myself? 

The documentation is hosted from [here](https://github.com/grails/grails-doc/). In case you are willing to contribute, please feel free to reach out if you need help updating the documentation.

**Comment by fernando88to** [comment]
I made the pull request below

https://github.com/grails/grails-doc/pull/872
