### ISSUE TITLE
Error running grails -version and grails interactive cli

### ISSUE THREAD

**Issue by jessie-apollotech** [grails/grails-core#13119]
### Expected Behavior

Running grails -version on 6.0.0 should return the version of grails as well as JVM just like with 5.3.3

```
$ grails -version
| Grails Version: 5.3.3
| JVM Version: 11.0.17
```

### Actual Behaviour

Running grails -version produces an error
```
$grails -version
grails: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by grails)
grails: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by grails)
```

why is the grails command now dependent on GLIBC? 

### Steps To Reproduce

1. install java via sdkman: 
  sdk install java 11.0.17.fx-zulu; sdk use java 11.0.17.fx-zulu
2. install grails via sdkman:
  sdk install grails 6.0.0; sdk use grails 6.0.0
3. try grails version:
  grails -version

### Environment Information

$lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal

$ java -version
openjdk version "11.0.17" 2022-10-18 LTS
OpenJDK Runtime Environment Zulu11.60+19-CA (build 11.0.17+8-LTS)
OpenJDK 64-Bit Server VM Zulu11.60+19-CA (build 11.0.17+8-LTS, mixed mode)

### Version

6.0.0

**Comment by jessie-apollotech** [comment]
I checked the other grails binaries installed by sdkman.
grails 6.0.0 switched to dynamically linked binary? the previous versions where just shell scripts. :(

```
~/.sdkman/candidates/grails$ ldd 4.0.11/bin/grails
        not a dynamic executable
```

```
~/.sdkman/candidates/grails$ ldd 5.3.3/bin/grails
        not a dynamic executable
```

```
~/.sdkman/candidates/grails$ ldd 6.0.0/bin/grails
6.0.0/bin/grails: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by 6.0.0/bin/grails)
6.0.0/bin/grails: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by 6.0.0/bin/grails)
        linux-vdso.so.1 (0x00007ffc55ba6000)
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fd9b185e000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fd9b1842000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fd9b1650000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fd9b1501000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fd9b6027000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fd9b14e6000)
```

**Comment by matrei** [comment]
In the Grails 6.0.0 cli the options are:
```
Options:
  -h, --help         Show this help message and exit.
  -v, --verbose      Create verbose output.
  -V, --version      Print version information and exit.
  -x, --stacktrace   Show full stack trace when exceptions occur.
```
It does however not print the Java version.

**Comment by jessie-apollotech** [comment]
> In the Grails 6.0.0 cli the options are:
> 
> ```
> Options:
>   -h, --help         Show this help message and exit.
>   -v, --verbose      Create verbose output.
>   -V, --version      Print version information and exit.
>   -x, --stacktrace   Show full stack trace when exceptions occur.
> ```
> 
> It does however not print the Java version.

Hi. What I am pointing out is that the grails 6.0.0 cli is now a binary when it was previously a shell script. 
This new binary does not run on distributions that do not have GLIBC_2.32 and GLIBC_2.34.

IMHO this is a step backwards as it breaks compatibility with older LTS linux distributions.

I will tinker around some more and see if a workaround can be found i.e. using the script from 5.3.3 instead.

**Comment by guillermocalvo** [comment]
Hi @jessie-apollotech

> Running grails -version on 6.0.0 should return the version of grails as well as JVM just like with 5.3.3

As @matrei noted, in the latest CLI the option is not `-version` but `-V` or `--version`.

We are adding back JVM version, because it was removed by mistake (see https://github.com/grails/grails-forge/pull/226).

> What I am pointing out is that the grails 6.0.0 cli is now a binary when it was previously a shell script.

That's correct. Grails CLI is now a binary, which runs faster and allows for offline creation of Grails applications.

> This new binary does not run on distributions that do not have GLIBC_2.32 and GLIBC_2.34.
>
> IMHO this is a step backwards as it breaks compatibility with older LTS linux distributions.

The binary is compiled against ubuntu-latest to make sure all the latest security patches are applied. Therefore it may not run on environments where `libc` is not up to date. Upgrading your Linux distribution should fix the problem. Thanks for your understanding.

**Comment by aadrian** [comment]
@guillermocalvo 

> The binary is compiled against ubuntu-latest to make sure all the latest security patches are applied. 

Sorry but this is a huge step backwards - not being able to use Grails on Ubuntu LTS (those that are currently supported) :( 

> Upgrading your Linux distribution should fix the problem. 

This is not under the control of users in most corporate environments !


> ...That's correct. Grails CLI is now a binary,..

Others already fixed the issue by not compiling statically against GLIBC  https://github.com/babashka/babashka/issues/826 

Since Grails 6 requires at least Java 11, there are no more issues ( as described by @ilopmar in https://github.com/oracle/graal/issues/2691#issuecomment-674818748  )

**Comment by unicolet** [comment]
I just launched a Github codespace and ran head first into this issue :cry:

**Comment by jamesfredley** [comment]
In Grails 6 the CLI switched from Grails Shell CLI to Grails Forge CLI which is what you get from sdkman.   Grails Forge CLI is only focused on app generation and `create-*` commands.  So after creating an app, you might use it to add controllers, services, etc, and rarely use it after that.

Grails Forge CLI is completely unaware of the grails application, including plugins and does not include or call Gradle.  It does not execute custom Grails Scripts.   This is very different from the pre Grails 6 CLI.

Since sdkman is distributing the platform specific grailvm binaries of Grails Forge CLI, you can always grab the shell script version from https://github.com/grails/grails-forge/releases/ or use https://start.grails.org/ to kickstart your new app.  https://start.grails.org/ is also what powers New Project -> Grails Application Forge in IntelliJ.

![image](https://github.com/user-attachments/assets/8c6c857e-7bb4-4a08-b415-522f82f6c7e5)
