### ISSUE TITLE
Webjars broken in grails

### ISSUE THREAD

**Issue by xpusostomos** [grails/grails-core#13117]
### Expected Behavior

I've long thought it would be better if the default grails create-app didn't have copies of javascript, i.e. jquery, popper, bootstrap, but rather if it used webjars, which seems a cleaner way of doing it.

Be that as it may, it often seems impossible to get webjars working with grails... although they work sometimes... and it's hard to know who to blame.

Anyway, take a clean grails application:
```
grails create-app myApp
```

Add the following line to the build dependencies:
```
    implementation "org.webjars:popper.js:1.16.1-lts"
```

And you get the following error:
```
> Task :assetCompile FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':assetCompile'.
> java.util.concurrent.ExecutionException: java.lang.Exception: BabelJs Engine initialization failed.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 2s
1 actionable task: 1 executed
```

I can't figure out what that means. It does successfully expand the webjar into the build/assets directory which is good. Altering application.js to either remove popper or to change popper to be the full path doesn't help:
```
//= require /webjars/popper.js/1.16.1-lts/umd/popper.min.js
```

and you can remove all the other javascript and it doesn't help:

```
//= require_self
```

So even though this webjar javascript seems to be merely sitting there unused and harmless in the build/assets, it kills the build.

Other webjars do seem to work:
```
    implementation 'org.webjars.npm:jquery-datetimepicker:2.5.21'
```

```
//= require jquery-3.5.1.min
//= require popper.min
//= require /webjars/jquery-datetimepicker/2.5.21/build/jquery.datetimepicker.full.js
//= require_self
```

### Actual Behaviour

The above build error occurs. It seems to me that grails should fully support webjars out of the box, at a bare minimum the standard ones: popper, bootstrap, jquery etc.

Bonus points if create-app is changed to use webjars.

### Steps To Reproduce

1. grails create-app myApp
2. add "implementation "org.webjars:popper.js:1.16.1-lts"" to the build dependencies
3. ./gradlew bootWar

### Environment Information

Windows
Java 17
gradle 7.6.2

### Version

5.3.3

**Comment by guillermocalvo** [comment]
Hi @xpusostomos! Thanks for reporting this issue.

I've been looking into the problem and the root cause is that you are using Java 17, which is not fully supported by Grails yet.

I followed your steps and created a demo application: https://github.com/guillermocalvo/grails-demo-webjars/

[As you can see here](https://github.com/guillermocalvo/grails-demo-webjars/actions/runs/6719225126), it builds successfully using Java 8 and Java 11 but unfortunately [BabelJs Engine initialization fails on Java 17](https://scans.gradle.com/s/ukdv5ui3rc6sy/failure#1).

> Other webjars do seem to work.

The reason is `org.webjars:popper.js:1.16.1-lts` contains the same library in three different flavors: CJS (CommonJS), ESM (ES Modules), and UMD (Universal Module Definition). On the other hand, `org.webjars.npm:jquery-datetimepicker:2.5.21`, only contains UMD. If we just stick to UMD, `asset-pipeline-gradle` will process the webjar without any errors.

I prepared a workaround in case you can't downgrade your JRE (which is the recommended option):
- https://github.com/guillermocalvo/grails-demo-webjars/pull/1/files

It fixes the problem by excluding CSJ/ESM versions of the popper.js webjar.

I hope this reply is useful and helps you solve the problem. Please feel free to reopen the issue if you find something else that doesn't work as expected.
