### ISSUE TITLE
The 6.0 document is in urgent need of an update.

### ISSUE THREAD

**Issue by hiarcs** [grails/grails-core#13116]
### Expected Behavior

Currently, due to the removal of many CLI supports and the lack of corresponding updates in the documentation, it is unclear how to perform certain actions that were supported in older versions. For example, is '--profile=rest-api' now completely equivalent to the new 'create-restapi'? How to use 'generate-all'? Why does running 'war' only result in a plain war file, and how to view the current environment's JDK version (the old '-v' option used to display both Grails and JDK versions)?

I personally do not quite understand why the CLI has been weakened to this extent. Considering the existence of https://start.grails.org/ and the fact that creating Domains/Controllers is not difficult, the current version of the CLI seems unnecessary. Of course, I can switch to using Gradle to perform various tasks, but in the absence of documentation, some issues become difficult to resolve. Moreover, since obstacles are encountered right from the beginning when creating a project, I am very concerned that similar problems may exist in other parts, which makes it impossible for me to promote the new version within the team. Therefore, I would like to inquire if there are plans to update the documentation in the near future?"

### Version

6

**Comment by puneetbehl** [comment]
Thank you for pointing it out. I am actively working on it and will soon publish the updated documentation. Sorry for the inconvenience!

**Comment by lawries** [comment]
I think the whole set of documentation needs to be revised and updated.

It’s starting to look like a scrapbook and there are still references to code/functions in much older versions that have been depreciated. It makes things very frustrating. 


There are also screenshots of the old green theme which was changed how many years ago?

Most searches for Grails documentation lead to info that’s over 4/5 years old so when you user base relies heavily on the official documentation, it needs to be current.

The days of decent plugins for simple integrations also seem to be a thing of the past and we’re expected to go and find 3rd party plugins or rely on bloated Java packages.

I’ve often gotten to the stage where I give up and use another framework.

I really love Grails, but it needs more focus in the correct places.

**Comment by lifeweaver** [comment]
Agreed. It seems to be just a few people holding things together, just nine people since 2022 have committed, and most of them just one or two commits. It appears to be [puneetbehl](https://github.com/puneetbehl) like 99% of the time. I'd also like to say that the Guides should be reviewed as well, some have been superficially updated, but then contain reference to incorrect info. Example https://guides.grails.org/grails4/creating-your-first-grails-app/guide/index.html says it's for Grails 5.01 but mentions the old "/dbconsole".

Grails is great as long as you follow the convention, and it does help kickstart a project. However due to the small community, once you hit a problem you can't go find the solution online. And if you're trying to doing something custom, you are fighting the entire framework. Not to mention having to wait for it to be updated to use newer libraries, i.e. no Spring 6 until Grails 7, aka next year or something. 

I already plan to switch my Grails projects to just normal Spring boot, you can have GORM, GSPs, Groovy, Gradle, etc all with Spring boot, I don't think it will be very hard to switch over. And once I do, I'll have a much larger community to fall back on.

**Comment by KornKalle** [comment]
I can also agree to this. The state of the documentation also makes it impossible for our team to upgrade to grails 6. How should I tell our developers the changes and the advantages when there is no documentation?

They keep asking for the important stuff from their perspective (Spring 6, Java 17, Hibernate 6...) and are not very motivated to do so when we could also switch to plain Spring.

Currently it leads us to similar decisions like mentioned above from @lifeweaver when creating new projects.

**Comment by monetschemist** [comment]
> Thank you for pointing it out. I am actively working on it and will soon publish the updated documentation. Sorry for the inconvenience!

@puneetbehl thanks for taking on this task.  I am willing to help (for example, edit existing documentation) but unfortunately it seems that "the new way of doing things" is currently a mystery, at least when it comes to following common tasks that are no longer supported by the new `grails` command and do not appear to have tasks defined in `gradlew`:

- generate-controller
- generate-views
- generate-all
- install-templates

I see that the scaffolding plugin is referenced in the `build.gradle` file, though it's expressed as:

`implementation("org.grails.plugins:scaffolding")`

instead of

`compile "org.grails.plugins:scaffolding"`

as shown [here in the latest documentation](https://docs.grails.org/latest/guide/scaffolding.html). 

I'm presuming that this means the `generate-*` functionality is still available, but it's a complete mystery to me how to access it.

Do you have any pointers for those of us trying to figure out how to use scaffolding in Grails 6.0.0?  Somewhere to look in the source code?

**Comment by puneetbehl** [comment]
The latest documentation is updated and available at https://docs.grails.org/latest/
