### ISSUE TITLE
Domain Map Constructor - not setting LocalDateTime field

### ISSUE THREAD

**Issue by keithdv** [grails/grails-core#13277]
### Expected Behavior

Given a simple Domain class:

```groovy
import java.time.*

class MyDomain {
    LocalDateTime dateCreated
    public Integer Value = 1

    static constraints = {    }
}
``` 
Using the Groovy map constructor:

```groovy
        MyDomain domain = new MyDomain(dateCreated: created, Value: 2)
``` 

I expect domain.dateCreated to be equal to 'created'

### Actual Behaviour

The value of domain.dateCreated is null. 

### Steps To Reproduce

I made a brand new Grails 6.0.0 project with JVM 11.0.20.
Here is a repo: [repo](https://github.com/keithdv/MapConstructorIssueLocalDateTime)

### Example Application

https://github.com/keithdv/MapConstructorIssueLocalDateTime

### Version

6.0.0

**Comment by matrei** [comment]
Hi @keithdv, see if this helps with your issue: https://docs.grails.org/latest/ref/Database%20Mapping/autoTimestamp.html

**Comment by matrei** [comment]
`id`, `version`, `dateCreated` and `lastUpdated` are explicitly excluded from databinding on domain classes:
https://github.com/grails/grails-core/blob/eb8470c557539364b4b7434e7cce4695a8457987/grails-web-databinding/src/main/groovy/org/grails/web/databinding/DefaultASTDatabindingHelper.java#L77C8-L77C8

That's why you cannot set `dateCreated` with the map constructor.

**Comment by keithdv** [comment]
That answers it, thank you!!
