### ISSUE TITLE
Grails 6.2.1 Security Vulnerabilities in Spring Framework

### ISSUE THREAD

**Issue by pkvenu** [grails/grails-core#13834]
### Expected Behavior

There should not be any Critical or high security vulnerability in spring framework or remediation workaround. 

### Actual Behaviour

Grails 6.2.1 have the following Spring Framework Vulnerability.  I would like to know the impact for these vulnerabilities. Any guidelines on remediating these would greatly help.

CVE-2024-38809 - Medium - org.springframework - linux - 5.3.33.0
CVE-2024-22262 - High - org.springframework - linux - 5.3.33.0
CVE-2016-1000027 - Critical - org.springframework - linux - 5.3.33.0

### Environment Information

OS - Linux
JDK -17

### Version

6.2.1

**Comment by jamesfredley** [comment]
@pkvenu Grails `6.2.1` uses Spring Framework `5.3.39` which has fixed CVE-2024-38809 and CVE-2024-22262.  https://mvnrepository.com/artifact/org.grails/grails-bom/6.2.1


If you are seeing Spring Framework `5.3.33` in addition to `5.3.39`, it is likely due to `buildSrc/build.gradle`.  `buildSrc` has distinct version resolution from the main `build.gradle` file, but `buildSrc` dependencies are not included in generated `libs` or `distributions`, so they would not be introduced to test or production environments.

![image](https://github.com/user-attachments/assets/c4ad1069-d26f-41e1-818a-1896aac06628)



adding `grails-bom` to `buildSrc` will set the correct versions for `buildSrc`.

```
repositories {
    mavenCentral()
    maven { url "https://repo.grails.org/grails/core/" }
}
dependencies {
    implementation platform("org.grails:grails-bom:6.2.1")
    implementation "org.grails:grails-gradle-plugin:6.2.1"
    implementation "org.grails.plugins:hibernate5:8.1.0"
}
```

For Grails `6.2.2` apps generated by https://start.grails.org, `buildSrc` will be a non-default feature and when it is selected, it will apply `grails-bom`.

For CVE-2016-1000027, Grails Projects do not use the deprecated package `org.springframework.remoting.httpinvoker`.  Spring recommends not using this package and removed it entirely in Spring Framework 6.  Grails 7 will be on Spring Framework 6.2.

https://github.com/search?q=org%3Agrails%20org.springframework.remoting.httpinvoker&type=code
![image](https://github.com/user-attachments/assets/fb401ec2-79df-4d3f-8e73-b14ffe20009a)

**Comment by pkvenu** [comment]
@jamesfredley - thanks for the quick update. I just had a followup question on one more vulnerability. We see that grails package uses the OpenSAML -> XMLtooling package which has the following **CVE-2019-9628**. https://mvnrepository.com/artifact/org.opensaml/xmltooling

Is grails affected by this vulnerable or any guidance on remediation? 

Thankyou so much for the help

**Comment by jdaugherty** [comment]
From what I can tell, org.opensaml isn't a dependency of Grails by default.
