### ISSUE TITLE
GRAILS-10920: Config gets executed multiple times

### ISSUE THREAD

**Issue by graemerocher** [grails/grails-core#4925]
Original Reporter: nicholas
Environment: Not Specified
Version: 2.3.4
Migrated From: http://jira.grails.org/browse/GRAILS-10920

Just copying this from the mailing list:
http://grails.1312388.n4.nabble.com/Config-groovy-getting-executed-several-times-on-app-startup-td4651882.html

{code}
When I execute a 'run-app' command with Grails 2.3.3, Config.groovy is getting read several times and in some cases certain properties are getting overridden. 

For example, I'm trying to externalize the dataSource properties. When I print the output of grails.config.locations: 

if (System.properties["${appName}.config.location"]) { 
    grails.config.locations = ["file:" + System.properties["${appName}.config.location"]] 
} 
println grails.config.locations 

I see: 

[file:/etc/ami/AMIContentManager.properties] 
[file:/etc/ami/AMIContentManager.properties] 
| Running Grails application 
[:] 
[:] 
{code}

**Comment by davidkuster** [comment]
I've run into this myself and found it to be a weird quirk and somewhat problematic. Any insight as to why this is a won't fix?

**Comment by noullet** [comment]
As it will not be fixed, could you tell us if there is anything we can do on our side to fix this issue?

**Comment by jamesdh** [comment]
### Packaging Phase - NOT YET FORKED (hence JVM standard environment or command line JVM properties will show up here)
- Config load 1 - Log4J loads the config prior to loading the app, I'm guessing to determine log configuration
- Config load 2 - Catalina loads the rest of the webapp which again loads the configuration

### Run phase - FORKED (you need to specify JVM properties in the `jvmArgs` list within the `grails.project.fork.run` map if you want them to show up here)
- Config load 3 - Log4J loads the config...
- Config load 4 - Catalina loads the rest...

See http://grails.github.io/grails-doc/2.5.0/guide/commandLine.html#forkedMode and search for "jvmArgs" for more info. We've confirmed locally that if you disable forked mode, properties specified via command line or environment do show up in the run phase. Otherwise if in forked mode, it's necessary to specify them within the jvmArgs list. 

I hope this makes sense...

**Comment by noullet** [comment]
Thanks James for the detailed explanation, that makes sense to me! :+1:
