### ISSUE TITLE
Grails 3.0.1 Respond method Ambiguous method overloading

### ISSUE THREAD

**Issue by Schlogen** [grails/grails-core#610]
In 2.4.4 I could call the respond method in my controller and pass into it a map (Ex: `respond([name: "Joe"])`. Now I get the following exception

> Ambiguous method overloading for method grails.artefact.controller.RestResponder$Trait$Helper#respond. Cannot resolve which method to invoke for [class websockets.TestController, class java.util.LinkedHashMap, class java.util.LinkedHashMap] due to overlapping prototypes between: [interface grails.artefact.controller.RestResponder, class java.lang.Object, interface java.util.Map] [interface grails.artefact.controller.RestResponder, interface java.util.Map, class java.lang.Object]

**Comment by jeffbrown** [comment]
I kind of see what is going wrong.  We have the same problem with 2.4.4 but it manifests kind of the other way around.  In 2.4.4 if you invoke something like ```respond([name: 'Joe'], [:])``` I think the ambiguous method problem will show up.  Will get it sorted out.  Thanks for the feedback.

**Comment by jeffbrown** [comment]
The tests at https://github.com/grails/grails-core/blob/66c8c7b097b136eb131421e400aef0a8622b4aff/grails-test-suite-web/src/test/groovy/grails/rest/web/RespondMethodSpec.groovy#L234 and https://github.com/grails/grails-core/blob/66c8c7b097b136eb131421e400aef0a8622b4aff/grails-test-suite-web/src/test/groovy/grails/rest/web/RespondMethodSpec.groovy#L244 are now passing.

**Comment by Schlogen** [comment]
Thanks @jeffbrown !

**Comment by davidtinker** [comment]
You can work around this by wrapping your Map and registering a marshaller for your wrapper:

    class MapWrapper { Map map }

    JSON.registerObjectMarshaller(MapWrapper, { MapWrapper it -> it.map })

    respond new MapWrapper(map: [foo: "bar"])

**Comment by orubel** [comment]
Well problem here... we shouldn't have to wrap a JSON marchaller in every response in every method in every controller.

As this is just passing the resource to the MQ / handlerInterceptor, they are final handoff prior to sending to client and may want to handle formatting prior to return to client. This also simplifies as it is one single point for format handling rather than placing a service call in every controller/method.

**Comment by orubel** [comment]
There are still errors with this it appears; it seems to always assume a domain as a resource. A resource can be a linkedhashmap, a commandobject, an algorithm, a list, an enum, etc. The method needs to allow for a generic Object or Model to be passed or for for passed Object to be easily converted to the generic type.

As of right now, this is still broken as render does not work with 'after' in handlerInterceptor' and this ('response') does not work with anything besides domain resource it appears.

**Comment by orubel** [comment]
Hmmm... Ok still a problem but you can get around by just returning result ...which I guess I should be doing anyway for what I am talking about. But this should be able to handle various data it seems.

**Comment by jeffbrown** [comment]
@orubel 

> Hmmm... Ok still a problem

In which version is it still a problem, and what is the problem?

**Comment by orubel** [comment]
3.0.4. I don't think this is an issue though as I see my problem. 'return' can handle response fine without sending view. Problem exists with handlerInterceptor and how 'after' method will ALWAYS expect VIEW if response is sent ... even if returning false (see https://github.com/grails/grails-core/issues/9175)

Opened ticket #9175 for this

**Comment by orubel** [comment]
So I guess you closed #9175 which I just opened without addressing it. Do I put my comments here then? I can see in the 'GrailsInterceptorHandlerInterceptorAdapter/postHandle' how it gets used but for some reason, the Handlerinterceptor 'after' method in a plugin cannot have a response sent from it otherwise 'return false' is not seen or is ignored .

**Comment by jeffbrown** [comment]
I don't see anything that looks like #9175 is related to this issue here.  The issue here had to do with problematic method overloading that prevented a `Map` from being passed as an argument to the `respond` method.

**Comment by jeffbrown** [comment]
@orubel I see a bunch of confusing comments, some of which you have deleted after posting.  One was the following:

> So I guess you closed #9175 which I just opened without addressing it.

I didn't close #9175.

I am not sure if you are saying that you think #610 is still broken or not.  You said the following:

> Ok still a problem but you can get around by just returning result

Is that related to #610, #9175, both, or neither?

**Comment by orubel** [comment]
Yeah sorry I corrected myself on slack but not here; I just removed the comment here. I am still trying to get used to issues in github vs Jira. My apologies.

This is working fine and I can work around... render, respond,return are my options and I am using return in controller to get around this. But this creates new issue of #9175 wherein 'after' method in handler interceptor causes error in dispatcher because you are sending response and returning 'false' in 'after' method which sets view/viewname to null.

**Comment by orubel** [comment]
#9175 may not be related but in order to pass a custom map and NOT format, I had to 'return' rather than 'respond' and in the handlerinterceptor, I 'return false' so as not to return view (since these are api calls). This creates a dispatcher error. This is why I said it's slightly related... but only slightly in that you will see that error in the flow and don't want people to get confused.

**Comment by robcomptec69** [comment]
My code is still in version 2.4.x. My solution was to cast the Map being returned as an Object.

Example:
def result = [:]
respond result as Object, [status: HttpStatus.OK]
