### ISSUE TITLE
[Grails 2.4.4] DataBindingUtils does not handle dateCreated and lastUpdated attributes

### ISSUE THREAD

**Issue by felipecao** [grails/grails-core#642]
While trying to fix this issue: https://github.com/noamt/elasticsearch-grails-plugin/issues/62

I noticed that the problem actually lies on the call to new DatabindingApi().setProperties(), which eventually delegates for DataBindingUtils to take care of it. It seems like DataBindingUtils#bindObjectToDomainInstance does not bind dateCreated and lastUpdated.

I'm not sure this is really a bug or an expected behaviour on grails-core, but I've implemented a workaround on elasticsearch-grails-plugin side, although it'd be much nicer if Grails took care of it.

**Comment by jeffbrown** [comment]
This is by design.  The `dateCreated` and `lastUpdated` properties are special properties that GORM handles initializing and updating.  Those are supposed to be excluded from mass property binding.  They are explicitly excluded at https://github.com/grails/grails-core/blob/9f78cdf17e140de37cfb5de6671131df3606f2fe/grails-web-databinding/src/main/groovy/org/grails/web/databinding/DefaultASTDatabindingHelper.java#L78.  If you want them to be bindable (that would be unusual) you could configure them with `bindable: true` in the constraints block.

**Comment by jeffbrown** [comment]
See https://github.com/grails/grails-core/commit/2d71727c189c52994e9254b4bd5d57a74463050e and https://jira.grails.org/browse/GRAILS-11173.
