### ISSUE TITLE
Grails 3: Please add documentation on configuring plugins

### ISSUE THREAD

**Issue by ikakara** [grails/grails-core#650]
I'm sure this a newbie (to Grails3) user issue.  How do you configure grails plugins ... I've tried configuring build.gradle with the following:

dependencies {
  compile "org.grails.plugins:tomcat:8.0.21" // in 2.x this would be build, but "build" doesn't seem to be supported in 3

  // simplifies scaling spring-security
  compile "org.grails.plugins:cookie-session:2.0.17" // http://grails.org/plugin/cookie-session

  compile 'org.grails.plugins:spring-security-core:2.0-RC4'
  compile 'org.grails.plugins:spring-security-userstore:0.8.2'

}

I guess, I should ask, do 2.x plugins work with grails 3?

**Comment by jeffbrown** [comment]
No, Grails 2 plugins are not compatible with Grails 3.

**Comment by ikakara** [comment]
Well, that stinks!  Is there a timeframe for when the major 2.x plugins from https://github.com/grails-plugins will be migrated to 3?  The one I care about the most is spring-security-core.  

Is there a new roadmap?

**Comment by jeffbrown** [comment]
> Well, that stinks! Is there a timeframe for when the major 2.x plugins from https://github.com/grails-plugins will be migrated to 3? The one I care about the most is spring-security-core.

There is no single timeline for all of those plugins.  They are mostly managed independently of each other.  Some of them have already been ported, some are in the process of being ported, some will eventually be ported and some may not need to be ported.  Spring Security in particular has been discussed at https://groups.google.com/forum/#!topic/grails-dev-discuss/jOF0jw_BiCs and other places.  One thing to consider there is Spring Boot changes how some of this works and a lot of folks may not even want a plugin in order to use Spring Security in a Grails 3 app.  There will be a plugin and it will be helpful but it won't play the same roles that the Grails 2 plugin plays and not having it really isn't a show stopper.  Depending on your application's requirements, it might just make sense to secure the app the Spring Boot way.

**Comment by jeffbrown** [comment]
A number of Grails 3 plugins have already been published at https://bintray.com/grails/plugins.

**Comment by allenathealthstack** [comment]
Thanks Jeff.  

Is there a team/group discussing the future of Grails?  I'm a long time Grails user (since 1.3.4), and I'd like to add my 2 cents if possible.  I love grails and love plugins, and utilize many of them.  But imho, grails and their plugins need to be more SOA (service oriented architecture), rather than "library" (that you compile into your code).  

For example, I stopped using GORM and preferred services to get/put stuff into a datastore service (like amazon s3, dynamodb, etc).  Grails services naturally fit w/ SOA.  Yes, there's nothing stopping me (or any developer) from using SOA today w/ grails ... EXCEPT, the boiler plate coding that has to be written to configure (aka locate), call (SOA) services via REST API, gracefully handle retries/failures, etc.  My point is that the future of coding isn't writing "stand-alone" apps, it's writing services that probably utilize many other services.  And making that easier should be the focus of the next generation of grails.  Assume the future is SOA (which it is), and create a platform that makes that easier for developers.

**Comment by ikakara** [comment]
Thanks Jeff.

Is there a team/group discussing the future of Grails? I'm a long time Grails user (since 1.3.4), and I'd like to add my 2 cents if possible. I love grails and love plugins, and utilize many of them. But imho, grails and their plugins need to be more SOA (service oriented architecture), rather than "library" (that you compile into your code).

For example, I stopped using GORM and preferred services to get/put stuff into a datastore service (like amazon s3, dynamodb, etc). Grails services naturally fit w/ SOA. Yes, there's nothing stopping me (or any developer) from using SOA today w/ grails ... EXCEPT, the boiler plate coding that has to be written to configure (aka locate), call (SOA) services via REST API, gracefully handle retries/failures, etc. My point is that the future of coding isn't writing "stand-alone" apps, it's writing services that probably utilize many other services. And making that easier should be the focus of the next generation of grails. Assume the future is SOA (which it is), and create a platform that makes that easier for developers.

**Comment by jeffbrown** [comment]
> But imho, grails and their plugins need to be more SOA (service oriented architecture), rather than "library" (that you compile into your code).

The mailing list at https://groups.google.com/d/forum/grails-dev-discuss is probably a better forum to discuss that.  Please post a note there.

**Comment by graemerocher** [comment]
Closing as this seems to be discussion appropriate from the mailing list rather than an issue

**Comment by AkhilPatro** [comment]
HI i am using the grails 3 ,i have  faced a problem  the use case is like 
i am in a list page like http://localhost:8080/category/index its listing  page, here if i click an element it will take to the edit page now the url is  http://localhost:8080/category/edit/5 in this page i have a form and going to submit the form to save on submiting the form the url is changing to
http://localhost:8080/category/edit/save?id=5  and it should redirect  to the action "save
 but redirecting to "edit"  even the same is not reflecting in the redirection .
So Please any one suggest on this.
thanks
Akhil
