### ISSUE TITLE
Grails 2.5.0: resource mapping, that only has save action creates the wrong link

### ISSUE THREAD

**Issue by mariodavid** [grails/grails-core#683]
In a Grails 2.5.0 (2.4.4 as well) app, if i create a resource `'book'`, that only has a save action and is mapped by a restful url mapping like the following: 

    "/books"(resources: 'book', includes: ['save'])

the creation of a link to the corresponding collection url results in a wrong url:

    <g:link url="[resource: 'book']" /> --> /book/index
    or:
    <g:form url="[resource: 'book']" method="POST" /> --> /book/index
    
The expected behavior would be to get the following url: `/books`
This is even true, if the generic url mapping `"/$controller/$action"` is not avaliable in `UrlMappings.groovy`.
If the includes attribute is removed in the `UrlMappings.groovy`, everything works as expected.

You can see a example at https://github.com/mariodavid/grailsResourceIssue

**Comment by graemerocher** [comment]
There is no bug here, by defining `includes: ['save']` you have essentially disabled all other URL mappings except the one for the save action. So to get a correct link for a `<form>` you need to map to that action:

      <g:form url="[resource:'book', action:'save']" method="POST">

As for the creation of links to the `index` action, this is the default fallback mapping kicking in, otherwise what would you want Grails to do? Throw an exception? We could certainly add a setting to throw an exception if a URL mapping doesn't match anything to avoid confusion instead of just falling back to creating the default pattern but that would be a new feature and would have to be disabled by default to avoid a breaking change
