### ISSUE TITLE
Grails 2.5.0: Filters, request.JSON, and command objects don't play nice

### ISSUE THREAD

**Issue by obildtsen** [grails/grails-core#688]
We have some filters that make tweaks to `params` values on incoming requests.  When using Grails 2.2.5, these worked great no matter the incoming request content-type.  Any controller action that used a command object got the modified values set properly.

We're currently upgrading to 2.5.0, and noticed that for incoming requests that set `content-type: application/json`, the params are empty by the time our filters execute.  The data has already been parsed into `request.JSON` and the `params` are empty.  

Fair enough, the filter can be changed to also modify `request.JSON` values.  The trouble with that solution is that if the filter does anything with `request.JSON`, the command object does not get populated.

Example filter:
```
    all(controller: '*', action: '*') {
        before = {
            request.JSON.someValue = "someModifiedValue"
        }
    }
```

Example controller action:
```
    def create(MyCommand command) {
        assert command.someValue == "someModifiedValue"  // BOOM if request had 'content-type: application/json'
    }
```

Is there a workaround, preferably making it so that filters execute prior to the automated parsing of the request into `request.JSON`...?

**Comment by jeffbrown** [comment]
>  We're currently upgrading to 2.5.0, and noticed that for incoming requests that set content-type: application/json, the params are empty by the time our filters execute. The data has already been parsed into request.JSON and the params are empty.

That doesn't make sense to me.  I don't think we are doing anything that would remove request parameters.  I know why the command object might not be populated but I don't know why request parameters would be disappearing.  Can you push a simple sample app to a public github repo and provide a link here along with instructions for reproducing that problem?

Thanks for your feedback.

**Comment by bobbywarner** [comment]
I'll try to help explain as @obildtsen and I work together.  Previously with Grails 2.2.5, you could post a JSON payload and access it with params in filters and controllers.  Now, you can only access the JSON payload with request.JSON and the JSON payload is removed from params.  Here's a test project: https://github.com/bobbywarner/grails-688-testapp

The test app has one filter which just tries to modify one of two JSON elements POST'ed in a request like this `request.JSON.bar = 'two'`. There are three unit tests:

https://github.com/bobbywarner/grails-688-testapp/blob/master/test/unit/paramstest/HomeControllerSpec.groovy

1) **Access JSON body from request.JSON**: this test fails because the JSON payload in the controller only has the JSON element that was updated in the filter (foo), but not the other original JSON element POST'ed (bar).
2) **Access JSON body from a command object**: this test fails because the filter did not have any effect on the JSON payload as both values are the same as what was originally posted.
3) **Access JSON body from params** like was previously possible in Grails 2.2.5, but this test fails because the request body is no longer populated in params, but rather request.JSON.

https://github.com/bobbywarner/grails-688-testapp/blob/master/target/test-reports/plain/TEST-unit-unit-paramstest.HomeControllerSpec.txt

So, the question is what (if even possible) is the correct way to modify a JSON payload in a filter and still be able to access the entire JSON payload in a controller?  The only solution I can think of is to use a custom `HttpServletRequestWrapper` to modify the request body in a regular servlet filter (or Spring interceptor) as opposed to using Grails filters.  Please let me know if you have any other suggestions.

**Comment by graemerocher** [comment]
Any updates?

**Comment by bobbywarner** [comment]
Here is a sample app with two unit tests.  The unit tests are pretty much the same but just call the different actions: https://github.com/bobbywarner/grails-688-testapp

Both tests fail:
https://github.com/bobbywarner/grails-688-testapp/blob/master/target/test-reports/plain/TEST-unit-unit-paramstest.HomeControllerSpec.txt

The first test shows that modifying the JSON request body in a filter overwrites all other values in the request body (foo is null), but ironically this same scenario works when running the app.  The second test shows that any changes made to the request body in a filter are ignored when using a command object ( @obildtsen 's primary point up above ), but once again different results when running the app.

So, is there anyway to modify a JSON payload in a filter and still be able to access the modified JSON payload in a controller?  And same question when using a command object?

**Comment by graemerocher** [comment]
So i'm not understanding, it seems you are highlighting issues with the unit testing framework as the running app behaves correctly?

**Comment by bobbywarner** [comment]
Yes, there appears to be a bug in unit testing as there's different results for tests vs running for both cases (with command object or without).  I've started looking into this, but if you have any suggestions, please let me know.

The question though is simply is it possible to modify a JSON payload in a filter when using command objects (second unit test, controller action two)?

**Comment by graemerocher** [comment]
I would suggest the behaviour that works in production mode is the correct one

**Comment by jeffbrown** [comment]
Part of the issue here is that the command object data binding mechanism reads the body of the request.  It doesn't refer to request.JSON.  The first time the system refers to request.JSON, the body has to be read.  Later when the command object binder attempts to read the body, the body has already been consumed.

We need to agree on what we really want to happen here.  If we can do that, making it happen may be fairly simple.  One thing we could do is add some handling so the command object binding mechanism may refer to request.JSON or request.XML instead of reading the body directly.  If we do that, maybe we should have a mechanism for arbitrary content types to be handled in the same way, as opposed to having special handling for JSON and XML.  I think we an probably just special case those, but that is something that will have to be considered.

**Comment by jeffbrown** [comment]
The ability for unit tests to re-read the input stream was actually a bug in my opinion.  See https://jira.grails.org/browse/GRAILS-11483 and https://github.com/grails/grails-core/commit/a28194b360a46ea5b94a0b243bd9546b407783f3#diff-968fb66f82020622cfbedfd6b9c64e2b.

**Comment by bobbywarner** [comment]
@jeffbrown Is there any downside to switching command objects to read from request.JSON (request.XML, etc) instead of the body?  Do we lose any command object functionality?  I like your idea of having a mechanism for arbitrary content types.

**Comment by graemerocher** [comment]
Filters are deprecated

**Comment by daptordarattler** [comment]
This issue exists in interceptors 
Env:
grailsVersion=5.2.5
grailsGradlePluginVersion=5.2.4
gormVersion=7.3.0
groovyVersion=3.0.11
org.gradle.daemon=true
org.gradle.parallel=true
#org.gradle.jvmargs=-Dfile.encoding=UTF-8 -Xmx1024M
org.gradle.configureondemand=true


any call I make to request.JSON in an interceptor breaks databinding in my controller actions for command object or domain instance.

How can I easily read the json body in the interceptor without calling request.JSON?

**Comment by jromero-onclick** [comment]
Some problem here.
Should we use Command Objects already?
