### ISSUE TITLE
Grails 3.0.1 - Latest wrapped request from ServletFilters are not available on GSP or Controllers

### ISSUE THREAD

**Issue by volnei** [grails/grails-core#702]
Since a simple filter wraps the request, I think that this request must be available on "grails context", but the request variable handles only the original org.apache.catalina.connector.RequestFacade.

I get this issue using SpringSecurity while I expect to use request.isUserInRole('SOMEROLE') has a wrong false response.

**Comment by graemerocher** [comment]
Not sure I understand the issue, please publish an example to github that reproduces the problem

**Comment by volnei** [comment]
Done 
https://github.com/volnei/requestwrapper

Thanks

**Comment by graemerocher** [comment]
This is a filter ordering problem, the `GrailsWebRequestFilter` runs before your filter and since you do not specify an order (via the `@Ordered` annotation) your filter runs afterwards. You need to use a `FilterRegistrationBean` to ensure your filter runs before Grails' filters:

https://github.com/grails/grails-core/blob/master/grails-plugin-controllers/src/main/groovy/org/grails/plugins/web/controllers/ControllersGrailsPlugin.groovy#L102
