### ISSUE TITLE
Grails 2.5.0: Reloading of domains and enums fails

### ISSUE THREAD

**Issue by zaccak** [grails/grails-core#715]
When I change my domains or enums I always get a failure in 2.5.0. It was working in 2.3.11 just fine:
.| Compiling 1 source files.
Error |
2015-05-19 19:11:03,537 [FileSystemWatcher: files=#12 cl=groovy.lang.GroovyClassLoader@68b2a7ce] ERROR plugins.AbstractGrailsPluginManager  - Plugin [domainClass:2.5.0] could not reload changes to file [/Dev/z_ws/x/grails-app/domain/x/Y.groovy]: Ambiguous method overloading for method grails.spring.BeanBuilder#registerBeans.
Cannot resolve which method to invoke for [null] due to overlapping prototypes between:
	[interface org.codehaus.groovy.grails.commons.spring.RuntimeSpringConfiguration]
	[interface org.springframework.beans.factory.support.BeanDefinitionRegistry]
Message: Ambiguous method overloading for method grails.spring.BeanBuilder#registerBeans.
Cannot resolve which method to invoke for [null] due to overlapping prototypes between:
	[interface org.codehaus.groovy.grails.commons.spring.RuntimeSpringConfiguration]
	[interface org.springframework.beans.factory.support.BeanDefinitionRegistry]
   Line | Method
->> 745 | run in java.lang.Thread

**Comment by zaccak** [comment]
I've already raised the emum issue here: https://github.com/grails/grails-core/issues/703

**Comment by graemerocher** [comment]
Can't reproduce this either

**Comment by harleydude99** [comment]
I'm new to Grails, and was working through the Quick Start Guide and kept seeing this error preventing the hot load of code changes.  I consulted with former colleague Jeff Brown about the steps to reproduce.  I'm using Grails 2.5.0 on Windows 7.

1.  grails create-app TekDays
2.  cd to TekDays
3.  grails run-app
4.  open another cmd window
5.  cd to TekDays
6.  grails create-domain-class com.tekdays.TekEvent
7.  good output in 2nd cmd window, but see the error in the original window

Error 2015-07-24 10:14:24,520 [Thread-11] ERROR plugins.AbstractGrailsPluginMa
nager  - Plugin [domainClass:2.5.0] could not reload changes to file [C:\grails_
dev\TekDays\TekDays\grails-app\domain\com\tekdays\TekEvent.groovy]: Ambiguous me
thod overloading for method grails.spring.BeanBuilder#registerBeans.
Cannot resolve which method to invoke for [null] due to overlapping prototypes b
etween:
        [interface org.codehaus.groovy.grails.commons.spring.RuntimeSpringConfig
uration]
        [interface org.springframework.beans.factory.support.BeanDefinitionRegis
try]
Message: Ambiguous method overloading for method grails.spring.BeanBuilder#regis
terBeans.
Cannot resolve which method to invoke for [null] due to overlapping prototypes b
etween:
        [interface org.codehaus.groovy.grails.commons.spring.RuntimeSpringConfig
uration]
        [interface org.springframework.beans.factory.support.BeanDefinitionRegis
try]

Other times I'd see it while going further through the tutorial was each time I'd edit a domain or controller (no the BootStrap.groovy, nor a test class), the original cmd window wouldn't be able to load the changed file, and would show the error above.

Hopefully this helps.

**Comment by zaccak** [comment]
2015-09-17 15:17:44,466 [FileSystemWatcher: files=#13 cl=groovy.lang.GroovyClassLoader@402f8592] ERROR plugins.AbstractGrailsPluginManager  - Plugin [domainClass:2.5.1] could not reload changes to file [/Users/Z/grails-app/domain/Y/X.groovy]: Ambiguous method overloading for method grails.spring.BeanBuilder#registerBeans.
Cannot resolve which method to invoke for [null] due to overlapping prototypes between:
	[interface org.codehaus.groovy.grails.commons.spring.RuntimeSpringConfiguration]
	[interface org.springframework.beans.factory.support.BeanDefinitionRegistry]
Message: Ambiguous method overloading for method grails.spring.BeanBuilder#registerBeans.
Cannot resolve which method to invoke for [null] due to overlapping prototypes between:
	[interface org.codehaus.groovy.grails.commons.spring.RuntimeSpringConfiguration]
	[interface org.springframework.beans.factory.support.BeanDefinitionRegistry]
   Line | Method
->> 745 | run in java.lang.Thread

**Comment by sting2804** [comment]
i have the same error after upgrading Grails from 2.4.5 to 2.5.1. When i try to change some pice of code in a service on a controller, o got something like:

[FileSystemWatcher: files=#187 cl=java.net.URLClassLoader@202898d7] ERROR plugins.AbstractGrailsPluginManager  - Plugin [services:2.5.2] could not reload changes to file [/***/***/***/grails-app/services/com/***/***/ProtocolVisitService.groovy]: Cannot get property 'cacheOperationSource' on null object
Message: Cannot get property 'cacheOperationSource' on null object

But i don't use any cacheOperationSource..

**Comment by martin-fuhrer** [comment]
I just upgraded my app to Grails 2.5.5 and I get exactly the same error each time I change something in a controller. However the reloading seems to work, but the error message is really nasty. Has anybody found a workaround for this?

**Comment by yhdelgado** [comment]
I have Grails 2.5.6 and I get the same error. Is there any solution for this issue?
