### ISSUE TITLE
Grails 2.5.0: Using ContainerRenderer for JSON responds with 404

### ISSUE THREAD

**Issue by dmahapatro** [grails/grails-core#716]
_Tested in Grails 2.4.4 and Grails 2.5.0_

Using a `ContainerRenderer` to return custom JSON response yields a 404 http response unless we provide a blank gsp file for the particular controller and action. `respond` should decide on the content rendering to JSON even without the gsp being present.

Below is the sample app to replicate the issue. 

 Steps to reproduce:
-----
Just rename `grails-app/views/timeline/index.gsp` to something else and hit

`http://localhost:8080/ContentRenderingApp/timeline`

Now, revert back the renaming and hit again. A 200 response with body is seen.

Sample App:
------
https://github.com/dmahapatro/grails-content-rendering-app

Stackoverflow Reference:
-------
http://stackoverflow.com/questions/30264953/grails-rest-controller-responds-with-incorrect-content-type

**Comment by donalmurtagh** [comment]
As I mentioned in the Stackoverflow post, I suspect the problem is related to the use of a custom renderer, because if I use a marshaller instead, the problem does not occur.

Having looked at some other examples, which use a custom renderer (successfully), one difference I noticed is that whenever a container renderer is registered for a collection of `T`, a renderer is also registered that renders an individual `T`.

In this case, only a renderer for a collection of `T` was registered. I don't know why it should be necessary 
As I mentioned in the Stackoverflow post, I suspect the problem is related to the use of a custom renderer, because if I use a marshaller instead, the problem does not occur.

Having looked at some other examples, which use a custom renderer (successfully), one difference I noticed is that whenever a container renderer is registered for a collection of `T`, a renderer is also registered that renders an individual `T`.

In this case, only a renderer for a collection of `TimelineItem` is registered, there's no renderer for an individual `TimelineRenderer`. I don't see why this shouldn't be allowed, but it may be the root of the problem.

**Comment by domurtag** [comment]
As I mentioned in the Stackoverflow post, I suspect the problem is related to the use of a custom renderer, because if I a marshaller is used instead, the problem does not occur.

Having looked at some other examples, which use a custom renderer (successfully), one difference I noticed is that whenever a container renderer is registered for a collection of T, a renderer is also registered that renders an individual T.

In this case, only a renderer for a collection of T was registered. I don't know why it should be necessary
As I mentioned in the Stackoverflow post, I suspect the problem is related to the use of a custom renderer, because if I use a marshaller instead, the problem does not occur.

Having looked at some other examples, which use a custom renderer (successfully), one difference I noticed is that whenever a container renderer is registered for a collection of T, a renderer is also registered that renders an individual T.

In this case, only a renderer for a collection of TimelineItem is registered, there's no renderer for an individual TimelineRenderer. I don't see why this shouldn't be allowed, but it may be the root of the problem.
