### ISSUE TITLE
GRAILS-9016: NoSuchFieldError: r$sfields when extending class in a jar that is in the same package as domain class

### ISSUE THREAD

**Issue by graemerocher** [grails/grails-core#8817]
Original Reporter: esword
Environment: Not Specified
Version: 2.0.3
Migrated From: http://jira.grails.org/browse/GRAILS-9016

I apologize in advance, but there is no way to say this without being confusing: 

If you have a non-artifact class in your grails application that extends a base class from an included jar and the base class is in the same package as a domain class, then you cannot instantiate an instance of the child class (or otherwise reference the child class in any way) when running tests from the interactive shell or when running "grails run-app" from the command line.

The included example app (and associated test lib) shows the problem.  I kept the class files there so you have exactly what I ran with.  

Some additional info:

1) Running tests from the command line (e.g. grails test-app) works fine
2) "grails run-war" also works fine
3) It doesn't matter where the child class is placed - could be in grails-app/util or just src.
4) It doesn't matter whether the classes (parent or child) are groovy or java classes.  The problem occurs either way.
5) The problem does not appear if the base class is included in the grails app itself.  It only happens when the base class is in an external jar.
6) I thought that it doesn't matter what package the child class is in, but in the sample app the child class must be in the same package as the parent class.  In my real app I have tried putting the child class in another package and still get the error.
7) These two posts about two different plugins report similar behavior: 
* http://ondrej-kvasnovsky.blogspot.com/2011/08/how-to-add-vaadin-add-on-into-grails.html
* http://www.graniteds.org/jira/browse/GDSFLEX-34

**Comment by ikakara** [comment]
Maybe related to https://github.com/grails/grails-core/issues/8966

**Comment by aclement** [comment]
The very simplest thing I can do is give you an option to turn off the feature that gives you a performance boost by disallowing split packages. If you turn it on then split packages will be allowed but the infrastructure will have to go digging for every single thing that gets loaded to see where it comes from. I don't know what the impact to startup time will be.

However, you already have the ability to work around this problem by specifying inclusion patterns. Inclusion patterns override the built in patterns and the optimization that prevents split packages. If my split package is com.foo.bar then a `-Dspringloaded=inclusions=com.foo.bar..*` would mean everything in there will be made reloadable regardless of where it comes from. However, as I look through the code the additional bypassing of the hard coded patterns that recognize non reloadable types may not be ideal (it could really hit startup time). We haven't much testing of using inclusion patterns. If someone wants to test this out with me, let me know. I can give you some dev builds to try out in a realistic scenario (I don't have a realistic scenario here).

Someone above said:
> For others who stumble upon this bug report and are wondering if it applies to them, this also applies if the subclass is in a sub-package of the parent class's package.

It shouldn't (unless I misunderstand what you are describing). Sub packages are treated differently to their parent packages. If `com.foo.Type1` is in the jar, and you want `com.foo.bar.Type2` to be reloadable (and it comes from disk) that should be fine. If it isn't behaving that could be something else we should look into. 

Someone else said:
> Does "NoSuchFieldError: r$sfields" result from trying to treat a class as reloadable when it has already been designated non-reloadable due to its package, or vice-versa?

Yes, the former. The error says "I expected this class to be reloadable and it isn't". At some point we decided the class we are looking at is not reloadable, presumably because it shares the package name with a type that we previously found in a jar. 

> Will both cases give an error or only one?

If we accidentally made the stuff from the jar reloadable, because it shared a package name with stuff we initially encountered as class files on disk (and so made reloadable), that would do no harm but it would hurt performance. For every type you make reloadable, it gets heavily modified with indirection to support the possibility that it may change in the future. If it came from a jar it is probably a library and that change isn't going to happen so you've made it all reloadable for no benefit. This is basically what you'd be choosing if you specify -Dspringloaded=inclusions=com.foo.bar..* - however, the new proposed option 'allowSplitPackages' wouldn't cause this problem. That new option is going to cause you overhead at startup time as we have to dig into detail into every class to work out where it came from.

**Comment by graemerocher** [comment]
@aclement I hit this issue when specifying `-Dspringloaded=inclusions=grails.plugins..* ` where I had a reloadable classes in src/main/groovy/grails/plugins that extended from a non-reloading class in the `grails-core` JAR file in the `grails.plugin` package. So I'm not sure specifying inclusions is a valid workaround as it seems to cause the problem too?

**Comment by aclement** [comment]
Ok, I've added some test cases and debugged into things. There is a case where specifying inclusions will still trigger a problem like this because there is an override on the forced inclusion that prevents the type being made reloadable if we don't think we can watch it (i.e. it came from a jar). This then leads to an issue because there is a check called isTopMostReloadableType() that ensures we augment extra fields only into the top most reloadable types. It is assumed that types in the same package are all treated one way or the other (reloadable or not) - if they are not then isTopMostReloadableType() makes a mistake and doesn't add these new fields anywhere, hence the NoSuchFieldError. (i.e. the real reloadabletype types think they aren't the top most reloadable type, and the types from the jar that are not reloadable never get processed to make the top most reloadable type check).

I have been augmenting the code to cope with split packages (although I still don't like them...). I also addressed the issue I mentioned above about if you force inclusion we might be letting through things we shouldn't because the inclusion pattern check was bypassing all hardcoded checks. Now if a type does not match an inclusion pattern we will process it through the hardcoded checks.

I now have to get the tests passing again and we should be good to test something.

**Comment by graemerocher** [comment]
@aclement Thanks Andy!

**Comment by aclement** [comment]
Todays snapshot builds include my changes: 
http://repo.spring.io/webapp/browserepo.html?0&pathId=libs-snapshot-local:org/springframework/springloaded/1.2.4.BUILD-SNAPSHOT

that should make the `inclusions` option behave. I wanted to also try a more generic `allowSplitPackages=true` option but that needs a bit more work and I still worry will hurt startup time a lot.

**Comment by graemerocher** [comment]
@aclement Ok will try it today. Thanks!

**Comment by graemerocher** [comment]
@aclement I tested this out and the changes work, however I do get this message printed to the console now when I make a change to a controller:

		GRAILS-7799: Subtype 'org.grails.plugins.web.controllers.ControllersGrailsPlugin' of reloadable type grails.plugins.Plugin is not reloadable: may not see changes reloaded in this hierarchy (please comment on that jira)
		GRAILS-7799: Subtype 'org.grails.plugins.web.controllers.ControllersGrailsPlugin' of reloadable type grails.plugins.Plugin is not reloadable: may not see changes reloaded in this hierarchy (please comment on that jira)
		GRAILS-7799: Subtype 'org.grails.plugins.web.GroovyPagesGrailsPlugin' of reloadable type grails.plugins.Plugin is not reloadable: may not see changes reloaded in this hierarchy (please comment on that jira)
		GRAILS-7799: Subtype 'org.grails.plugins.web.GroovyPagesGrailsPlugin' of reloadable type grails.plugins.Plugin is not reloadable: may not see changes reloaded in this hierarchy (please comment on that jira)

I don't know why Spring loaded is trying to reload these classes as they are in a JAR file and they are not the classes I changed?

**Comment by graemerocher** [comment]
@aclement What would be nice is being able to exclude additional JARs that would otherwise be included by the inclusion. Something like:

     exec.jvmArgs "-Dspringloaded=inclusions=grails.plugins..*;jar.exclusions=grails-*"

Maybe this would avoid the error?

**Comment by aclement** [comment]
Interesting. A side effect of making the grails.plugin files from the jar reloadable. These 'other types' from other jars that extend the grails.plugin files are not made reloadable (they don't match the inclusion patterns) and that leads to the 'warning'. I'd rather avoid introducing even more inclusion/exclusion options as it is already a bit too complicated. What needs to be done is a smarter version of isTopmostReloadableType() - that is the check which currently can't cope with a type hierarchy being partly reloadable if the types within it share the same package and they are split across jars and disk. Let me try to do that.

**Comment by aclement** [comment]
I just committed some changes to make the test smarter. This should mean if you use `inclusions=grails.plugins..*` it will consider the files 'from disk' as reloadable but not those from the jar (that are using the same package name). The improved intelligence of the test should ensure it knows where the break in the type hierarchy is (which is the 'top most reloadable type') and add the appropriate extra members there. This also avoids confusion where other subtypes of the stuff in the jar that were in a different package found that they were not reloadable when their parents were.  Dev builds should have this in. I'm happier with this solution but it could do with some testing in real scenarios, I've only got some simple unit tests.

**Comment by graemerocher** [comment]
@aclement Thanks Andy, will test it out today

**Comment by graemerocher** [comment]
@aclement I have tested it and it works great, thanks! Would love a release of 1.2.4 :)

**Comment by aclement** [comment]
@graemerocher I'll do it in the next few days.

**Comment by longwa** [comment]
FYI, this problem is somewhat easier to run across now in Grails 3 because of the fact that inline plugins are compiled to JAR's now for multi-project builds.

For example, we have a `common` inline plugin module which shares the same package structure as our two applications. Anywhere we extend one of the classes in `common` (usually shared controller logic), we are getting the `r$sfields` error. I guess the easiest workaround is to just move to a different package.

I did create a Grails 3 test application that demonstrates the problem pretty easily. Just pull and do `gradle run` to see it.

https://github.com/longwa/grails3-field-error
