### ISSUE TITLE
Grails 2.5.0: `grails war` fails under Java 1.6

### ISSUE THREAD

**Issue by squarejaw** [grails/grails-core#8997]
According to the [Installation Requirements](http://grails.github.io/grails-doc/2.5.0/guide/gettingStarted.html#requirements), Grails 2.5.0 requires Java 1.6 or above, but the `war` command fails under Java 1.6.
```
Jun 3, 2015 3:36:38 PM org.codehaus.groovy.runtime.m12n.MetaInfExtensionModule newModule
WARNING: Module [groovy-all] - Unable to load extension class [org.codehaus.groovy.runtime.NioGroovyMethods]
Jun 3, 2015 3:36:38 PM org.codehaus.groovy.runtime.m12n.MetaInfExtensionModule newModule
| Building WAR file.....
Start of war build
| Precompiling Assets!.
| Error Error executing script War: java/nio/file/FileSystems (Use --stacktrace to see the full trace)
```
I'm guessing this is because [java.nio.file.FileSystems](http://docs.oracle.com/javase/7/docs/api/java/nio/file/FileSystems.html) only exists in Java 1.7 and above.

**Comment by squarejaw** [comment]
The asset-pipeline plugin appears to be the problem.  The plugin version was updated to 2.1.5 in https://github.com/grails/grails-core/commit/e596a382a3b94277eec7328eaa122cda40946a71 and that version uses the classes added in Java 1.7.  Looks like this means grails 2.4.5 is also affected.

Downgrading to asset-pipeline 1.9.9 in my project allows the war to be built.

**Comment by graemerocher** [comment]
Hmm @davydotcom may need to comment on Java 1.6 compatibility for asset pipeline

**Comment by davydotcom** [comment]
Yea decided to drop 6 compatibility in order to use the built in file scanning by glob pattern support built into Java 7... You can always go back to 1.9.9 but Java 6 is getting kinda old

**Comment by davydotcom** [comment]
Sorry about this but it was the only way to resolve the new file scanning reliably without commons io. You can always back down to 1.9.9 or upgrade your build to use Java 7

**Comment by graemerocher** [comment]
So I guess we need to consider downgrading the default version of asset pipeline for Grails 2.5 to 1.9.9

**Comment by allenhealthstack** [comment]
I suggest, adding a comment in BuildConfig.groovy for Java6 users, but default to the latest.  
```
    compile ":asset-pipeline:2.2.0" // for Java6 use 1.9.9
```

I apologize (in advance) for getting on the proverbial soapbox:
Imho, everyone should be moving to Java9.  Yes I know Java8 is brand spank'n new.  But that's my point.  I tend to think Java8 isn't "good enough" for how I want to write apps/services/etc - JIT compiled vs 'interpreted' is going away (in JAVA - I hope), just like PermGen needed go away.  We're moving toward a future, where we build apps, services, etc on top of other services (SOA) in the cloud.  The future is uploading "code bits" (as oppose to monolithic apps) into the cloud, and we "pay per execution" (not per box).  So execution of code is very short lived, ideally done in sub-ms.  So the Java language behavior of determining whether the JIT should compile (to native) or interpret is antiquated and no longer useful in a "pay per execution" environment.  Optimization (of code) will have to be rethought, etc.   The Java language needs to adapt to a "pay per execution" environment because it's already here (AWS Lambda).  And btw AWS Lambda doesn't support Java yet, because I imagine there's too much overhead creating/destroying JVMs and so the performance sucks.  Anyway, a more modular Java9 should help with that.  And I think grails needs to go through a reformation too.  The cloud is here to stay so everything from the language to the framework to developers need to adapt.

**Comment by ikakara** [comment]
I suggest, adding a comment in BuildConfig.groovy for Java6 users, but default to the latest.

    compile ":asset-pipeline:2.2.0" // for Java6 use 1.9.9

I apologize (in advance) for getting on the proverbial soapbox:
Imho, everyone should be moving to Java9. Yes I know Java8 is brand spank'n new. But that's my point. I tend to think Java8 isn't "good enough" for how I want to write apps/services/etc - JIT compiled vs 'interpreted' is going away (in JAVA - I hope), just like PermGen needed go away. We're moving toward a future, where we build apps, services, etc on top of other services (SOA) in the cloud. The future is uploading "code bits" (as oppose to monolithic apps) into the cloud, and we "pay per execution" (not per box). So execution of code is very short lived, ideally done in sub-ms. So the Java language behavior of determining whether the JIT should compile (to native) or interpret is antiquated and no longer useful in a "pay per execution" environment. Optimization (of code) will have to be rethought, etc. The Java language needs to adapt to a "pay per execution" environment because it's already here (AWS Lambda). And btw AWS Lambda doesn't support Java yet, because I imagine there's too much overhead creating/destroying JVMs and so the performance sucks. Anyway, a more modular Java9 should help with that. And I think grails needs to go through a reformation too. The cloud is here to stay so everything from the language to the framework to developers need to adapt.

**Comment by davydotcom** [comment]
I kinda agree with the java 6 comment block then again 1.9.9 has some bugs in it that can be a nuisance to deal with this mean I need to make a new 1.9.x version with fixes?

**Comment by squarejaw** [comment]
@davydotcom IMO that depends on how long you feel obligated to support older versions of Java.  I've seen an increasing number of libraries drop support for Java 6.  

Java 6 (and 7) are EOL (without a support contract) and I'm not sure how large of a user base is actually using newer Grails releases on Java 6.  Ideally I'd be using Java 8, but for now I'm locked into a Java 6 ecosystem.

**Comment by ikakara** [comment]
For Grails 2.x, there's no reason (except the additional work) not to support Java6.  If davydotcom is willing to create 1.9.x version with the latest bug fixes for asset-pipeline, the work would be limited to that.

**Comment by davydotcom** [comment]
thats a big (except) :)

**Comment by ikakara** [comment]
For Grails 3 and beyond, I think Grails has to take a massive jump forward (not an incremental one).  I've been doing grails since 1.3.x - I was using grails 1.3.7 until the past 18 months or so where I went to 2.3, 2.4 and now 2.5 very rapidly.  And the only reason I was able to do that, was because I changed jobs so I wasn't stuck w/ legacy stuff I built 4-5 years ago (on 1.3.7).  1.3.7 to 2.4/2.5.x is a huge improvement.  Right now, Grails 3 seems like a step back to me.  But I'm hopeful.  I just think, Grails3 (or some future version) should focus on cloud, and making it easier for developers to build/utilize SOA, as well as adapt to the future cloud model, of "pay per execution" rather than pay per box (albeit virtual).

Today, it's very common for assets in production to be served by a CDN.  There's no reason to have static assets served by the box that the web app (code) is on.   Like CDNs (do for assets), the cloud will execute code at the edges to provide a low latency response to every request regardless of where the request originates.  That's the future for cloud (at least AWS), and so the future of Grails needs to assume SOA, it's in the cloud, AND in a "pay per execution" environment.

**Comment by ikakara** [comment]
Sorry davydotcom for volutneering you like that! We (all of us grails developers), really do appreciate all the work that you and your biz does.  Asset pipeline is a huge improvement over resources.

**Comment by davydotcom** [comment]
just fyi there are plugins that transfer your assets to CDNs and cloud front also is a great candidate for grabbing these assets and serving them allowing you to preserve versioning of your static assets along with your server code. Grails 3 is by no means backwards in that regard. Agreed that we don't normally let grails server our assets though. We configure grails 2 and grails3 (via asset pipeline storagePath config) to export the compiled assets to the filesystem on startup and be served by nginx or upload them to a CDN. Depends on the environment. Also as of 2.2.x AP is able to cut  the storage used for those assets in half in your war or jar file but not even storing the non digested name files (however it will export non digested name files when it copies to an external storage path so that your CDN can behave properly in that scenario). 

As far as Grails 3 as a step back, I'd say its much easier to deploy grails 3 on cloud services like heroku or cloud foundry among others due to its new container style build based on spring boot. Build times are also greatly improved further allowing cloud build integrations like travis-ci to more quickly get you up and running. Also support for micro service profiles allow you to further lean up the stack for more responsive SPA designs among other things.

P.S. Thanks, yea not sure what kind of  time there will be for maintaining pre 2.x code as that not only requires maintaining the main asset-pipeline plugin but all the extension sass, less, coffee, etc. based plugins for that era

**Comment by ikakara** [comment]
I'm a big fan of Spring boot, and hence would love to use Grails3 in the manner that you describe.  I just can't yet, because I tend to utilize a lot of plugins, and many of which haven't made the transition to Grails3.  I feel I should contribute more to the Groovy/Grails (even Spring) effort, but alas the 'open source community' is stuck w/ me ranting ... lol  

I'm on Java8 (w/ some maintenance on Java7), but very much looking forward to Java9.  So I don't need pre 2.x code, but I imagine that Java6 is still used widely:

Java6 since Dec 2006 - potentially 8-9 years of Java6 projects
Java7 since Jul 2011 - at most 3-4 years of Java 7 projects
Java8 since Mar 2014 - at most < 1 year of Java8 projects

Java6 is no longer supported, so you have an out :)

**Comment by wijnand1** [comment]
Is there any reason why using (a recent version of) the asset pipeline should result in a runtime dependency for java 6 as well? 

I have a Grails 2.5.3 project with grails.project.target.level = 1.6 in the BuildConfig.

Using compile ":asset-pipeline:2.6.7" I can build a war just fine (using java 8 here)
However, deploying the WAR into Tomcat running on Java 6 it fails with
a java.lang.UnsupportedClassVersionError: asset/pipeline/utils/net/Urls : Unsupported major.minor version 51.0 (unable to load class asset.pipeline.utils.net.Urls)
Seems like all the asset.pipeline classes are compiled for Java 7 ?

If I switch to
compile ":asset-pipeline:1.9.9" it runs fine on Tomcat on Java 6.

The file scanning and obfuscation are mentioned as requiring Java 7 support, but that is all done compile time. Any reason it is compiling into Java 7 bytecode, and not following the project.target.version=1.6 setting for the assets plugin
