### ISSUE TITLE
Hyphenated URLs are actually camelCase

### ISSUE THREAD

**Issue by dpilafian** [grails/grails-core#9017]
The configuration for enabling hyphenated URLs does not seem to be sticking.

#### Setup:

**grails-app/config/application.yml**
```yaml
grails:
   web:
      url:
         converter: "hyphenated"
```

**grails-app/controllers/BookAuthorsController.groovy**
```groovy
class BookAuthorsController {
   def index() {
      }
}
```

#### Expect:
View to render at:
*http://localhost:8080/book-authors*

#### Actual:
*Page Not Found (404) error*
(however, incorrect camelCase URL *http://localhost:8080/bookAuthors* does work)

#### Environment:
````
Darwin Blade.local 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64
Grails Version: 3.0.1
Groovy Version: 2.4.3
JVM Version: 1.8.0_45
```

http://stackoverflow.com/q/29813085

**Comment by jeffbrown** [comment]
I will take a look at this in the next couple of days and get it straightened out.  Thanks for the feedback.

**Comment by jeffbrown** [comment]
I debugged this a bit tonight and see what is going wrong.

When https://github.com/grails/grails-core/blob/8373a40a4993b614bb85f87169ee1bb53e1dadb2/grails-web-url-mappings/src/main/groovy/org/grails/web/mapping/DefaultUrlMappingInfo.java#L86 executes, `servletContext` is null so the `applicationContext` ends up null there so the code falls into the `else` block and creates an instance of `CamelCaseUrlConverter`.  The reason that `servletContext` is null can be traced back to https://github.com/grails/grails-core/blob/8373a40a4993b614bb85f87169ee1bb53e1dadb2/grails-web-url-mappings/src/main/groovy/org/grails/web/mapping/DefaultUrlMappingEvaluator.java#L107.  When that code executes, `((WebApplicationContext)applicationContext).getServletContext()` evaluates to null because the servlet context has not been set yet.

Will track down a proper fix and get it working.

Thanks again for the feedback.
