### ISSUE TITLE
Grails 3.02:  grails run-app w/ application.yml 'context-path': '/test302' returns "Grails application running at http://localhost:8080 ..."; should return '... http://localhost:8080/test302'

### ISSUE THREAD

**Issue by ikakara** [grails/grails-core#9020]
Environment:
------------------
Window 8.1
Oracle JDK 
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)
```
> grails create-app test302
> cd test302

// Add the following to the application.yml
server:
    'context-path': '/test302'

> grails compile
> grails run-app
```
Returns "Grails application running at http://localhost:8080 in environment: development", even though the correct url http://localhost:8080/test302

**Comment by graemerocher** [comment]
broken by https://github.com/grails/grails-core/commit/c718ae25ffabeee1a5dcb4ccb980c6891005187a

Seems under some circumstance it is camel case? Maybe @jeffbrown can comment

**Comment by jeffbrown** [comment]
Does it work if you replace `context-path` with `contextPath`?

**Comment by ikakara** [comment]
It does!  I didn't realize that the context-path was changed.  There are a few stackoverflow issues w/ context-path, rather than contextPath.  I wonder if a comment should be added to them:
http://stackoverflow.wwwblogher.com/questions/29989050/grails-3-0-spring-security-server-context-path-issue
http://stackoverflow.com/questions/29721715/how-to-set-a-grails-3-app-to-use-a-root-context-path
http://stackoverflow.com/questions/29110598/grails-3-0-app-starts-on-unexpected-path-how-to-fix

**Comment by jeffbrown** [comment]
I think boot wants `contextPath`.  We could impose some trickery to support both or maybe we should just go with `contextPath`, clarify it in the docs and move forward like that.

Thoughts?

**Comment by jeffbrown** [comment]
Maybe I was wrong about part of that.  It seems that with 3.0.1 either `contextPath` or `context-path` will actually set the context path.  I thought that only `contextPath` would actually work and that the change at https://github.com/grails/grails-core/commit/c718ae25ffabeee1a5dcb4ccb980c6891005187a was coordinating what was printed to the console with the setting that would actually set the context path.

**Comment by ikakara** [comment]
Simplify: just support contextPath - it's easy enough to fix the application.yml if a developer has context-path and upgrades.

**Comment by anderskristian** [comment]
I have just being testing both from 

gradle bootRun

    contextPath: /test302 - Application works + log statement is correct

    context-path: /test302 - Application works + log statement missing /test302. And this is due to #8989 

grails>> run-app

    contextPath: /test302 - Application works + log statement is correct

    context-path: /test302 - Application works + log statement missing /test302. And this is due to #8989 


It seems to me that the system somewhere accepts both context-path and contextPath
From Servlet API 2.5 they added getContextPath() see: http://docs.oracle.com/javaee/5/api/javax/servlet/ServletContext.html
And the API is camel Case (due to nature of Java language - I assume)

In Jersey they also refer to a key called "jersey.config.servlet.filter.contextPath"

In Spring Boot I found http://stackoverflow.com/questions/20405474/spring-boot-context-root
Here the answer is
   
   server.contextPath=/mainstay

To conclude:

I think that "contextPath" is a correct key and easy to explain.

That it works on both "contextPath" and "context-path" could be the nature of spring-boot property reader ?? - where "-" could be changed to camel case. In this case "-p" becomes "P"

An improvement could be to warn about "context-path".

Adding code ( to GrailsApp.groovy )

    String contextPath = app.config.getProperty('server.context-path', '')
    if(contextPath) {
        println ("server.context-path is deprecated, please use server.contextPath")
    }
    +++ code to print the non null value them +++

**Comment by ikakara** [comment]
Whatever the "fix", don't forget to update the documentation: https://grails.org/single-page-documentation.html - In the helloworld example, the doc uses context-path

**Comment by jeffbrown** [comment]
I think we should move toward using `contextPath` and update the docs accordingly.  We can also rig up the run script so that if `contextPath` is not used and `context-path` is used, we use the `context-path` value for the console output so the console is consistent with the actual app context and log a warning about it to help folks know to use `contextPath`.

The confusion around this was largely my fault.  When the change was produced to log `contextPath` instead of `context-path`, I was under the impression that `context-path` was not working as far as setting the actual context path, and I was wrong about that.  Apologies.

What say ye?

**Comment by anderskristian** [comment]
I agree move foreward with contextPath
It was me that introduced the fix #8989 - I did not know that context-path was an option.
So apologies from me....

I will make pull request ... (or probably 2 pull requests to get the documentation too..) unless you think otherwise.

**Comment by graemerocher** [comment]
Thanks @anderskristian

**Comment by jeffbrown** [comment]
@anderskristian Excellent.  Thanks for all of your help.
