### ISSUE TITLE
Render method in an Interceptor doesn't render the view template, you only get a blank page.

### ISSUE THREAD

**Issue by olavgg** [grails/grails-core#9069]
Render doesn't work properly with the following interceptor:

```java

import static org.springframework.http.HttpStatus.NOT_FOUND

class AdministrationInterceptor {

    AdministrationInterceptor(){
        match(namespace: 'administration')
    }

    boolean before() {
        log.debug "running administration interceptor before()"
        render view: '/notFound', status: NOT_FOUND
        return false
    }

    boolean after() { true }

    void afterView() {
        // no-op
    }

}
```

Example application: https://github.com/olavgg/modelandviewerror

Goto http://localhost:8080/administration/dashboard/ and you get a blank page, the default notFound.gsp is not being rendered.

**Comment by jeffbrown** [comment]
I think I see what is happening.

When an interceptor returns false we end up at https://github.com/spring-projects/spring-framework/blob/261e37485a76586fddc858fb0896006fe92139f5/spring-webmvc/src/main/java/org/springframework/web/servlet/DispatcherServlet.java#L955.  Because that is returning, we never get to https://github.com/spring-projects/spring-framework/blob/261e37485a76586fddc858fb0896006fe92139f5/spring-webmvc/src/main/java/org/springframework/web/servlet/DispatcherServlet.java#L971 and `processDispatchResult` never gets called.

Working on a solution.

**Comment by ajdevries** [comment]
``` groovy
package demo

import grails.gsp.PageRenderer

class TenantInterceptor {

    def tenantService

    PageRenderer groovyPageRenderer

    TenantInterceptor() {
        matchAll()
    }

    boolean before() {
        log.info "In TenantInterceptor"
        Tenant t = Tenant.findByName(tenantService.name(request.forwardURI))
        tenantService.tenantId = t?.id
        if (t == null) {
            def o = groovyPageRenderer.render view: '/tenantNotFound'
            render o
        }
        t != null
     }

    boolean after() {
        true
    }

    void afterView() {
        // no-op
    }

}
```
