### ISSUE TITLE
method security problems with Grails 3.0.3

### ISSUE THREAD

**Issue by akistanov** [grails/grails-core#9096]
Problems metntioned in #9092 were not completely fixed with grails 3.0.3 release. 
`Class name [org.grails.spring.aop.autoproxy.GroovyAwareAspectJAwareAdvisorAutoProxyCreator] is not a known auto-proxy creator class` still happens until you directly call `GroovyAwareAspectJAwareAdvisorAutoProxyCreator` class before invoking `GrailsApp.run(Application)`. For example by creating new `GroovyAwareAspectJAwareAdvisorAutoProxyCreator` instance:
`
class Application extends GrailsAutoConfiguration {
    static void main(String[] args) {
        new GroovyAwareAspectJAwareAdvisorAutoProxyCreator()
        GrailsApp.run(Application)
    }
}
`

And even with this workaround app failed with 
`java.lang.IllegalArgumentException: org.springframework.security.config.annotation.method.configuration.EnableGlobalMethodSecurity is required`
if you add
`@EnableGlobalMethodSecurity(prePostEnabled = true)` to the `SecurityConfiguration`.

**Comment by graemerocher** [comment]
Please upload an example to Github that reproduces the issue

**Comment by dunkelrot** [comment]
Please take a look at:
https://github.com/dunkelrot/grail-auth-exception

I had the same issue and "fixed" it within the Application class. Take a look at the "doWithSpring" closure. 

The issue shows up due to the use of MethodSecurityConfiguration as a Spring bean, this class sets @EnableGlobalMethodSecurity(prePostEnabled = true)

I don't know how to fix that in Grails. I guess that should be done by a plugin that brings Spring Security to Grails.
