### ISSUE TITLE
Integrate with Waffle.io

### ISSUE THREAD

**Issue by driverpt** [grails/grails-core#9110]
As title says

**Comment by jeffbrown** [comment]
Related to https://github.com/grails/grails-core/pull/8964

**Comment by jeffbrown** [comment]
The core dev team has on site in person dev meetings next week during which we will discuss.

@driverpt I think Waffle.io is probably a good idea and we will discuss and make a decision about that, but I am curious to know why you care what tools and process we use.  Is it because Waffle.io will give you improved visibility into what we are doing, or something else?

Thanks for the feedback.

**Comment by driverpt** [comment]
Hello, i created this issue as a suggestion. I use it on my personal
projects and it gives a "simplified" view over all the issues and todo's in
those projects.

I think it could contribute to people contribute more to the Grails
Framework.

Please see this as a suggestion and not as an "issue"

Os melhores cumprimentos,
Best Regards,
Met vriendelijke groet,

Luís Duarte

On Thu, Jul 16, 2015 at 11:13 AM, Jeff Scott Brown <notifications@github.com

**Comment by jeffbrown** [comment]
Seeing a first fly in the ointment.  We have closed issues showing up in our Waffle backlog column.

https://github.com/waffleio/waffle.io/issues/1798.
