### ISSUE TITLE
Getting GroovyCastException with casting to JSON in unit/integration-testing, when using respond

### ISSUE THREAD

**Issue by anielsen3** [grails/grails-core#9140]
When I use `respond dto` in my controller, it works in production. But in testing it sometimes fails, depending on the order tests are run:

`org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object 'respondbug.MyDto@47ed5990' with class 'respondbug.MyDto' to class 'grails.converters.JSON'`

I've created a small application that demonstrates the error: https://www.dropbox.com/s/gxe1efbqk54c2qp/respondBug.zip?dl=0

If you run `grails test-app unit: MyDtoSpec MyControllerSpec` it gives the error.

if you run `grails test-app unit: MyControllerSpec MyDtoSpec ` it doesn't.

**Comment by graemerocher** [comment]
This issue is tricky to fix as it relates to internal order of meta class creation. I'm cautious to start messing with that area in 2.5.x especially as we are moving to traits in 3.x

As a workaround you can add this to your setup method:

	void setup() {
		GroovySystem.metaClassRegistry.removeMetaClass(MyDto)
	}

As an explanation as to why this is happening, the reason is that if `MyDtoSpec` is run first then Groovy creates a MetaClass for `MyDto` which is used in subsequent tests. Since `MyDto` is just a regular Groovy class we don't track or remove its meta class state. 

Then when `MyControllerSpec` this adds the converters conversion methods to the `Object` parent class. Unfortunately, since the `MyDto` meta class is already created it doesn't get inherited via `Object`, which leads to the exception. By adding the aforementioned code it forces recreation of the meta class.

**Comment by anielsen3** [comment]
Alright, thanks for the explanation and the work-around.
