### ISSUE TITLE
Grails 3.0.4: Dynamic scaffolding doesn't use installed templates

### ISSUE THREAD

**Issue by nobeans** [grails/grails-core#9155]
Like before, dynamic scaffolding should respect the templates which is installed by `install-template` command. In addition, it would be reloaded after editing.

**Comment by hakanernam** [comment]
This problem seems to still exist. Installed Controller template is neither picked up upon application start nor reloaded when edited. Only after entering the command "generate-controller", installed and edited template is used in generating the controller.

###Example:
https://github.com/hakanernam/scaffolder.git

- Add method to Controller template. Edited file is not honored.
- Generate ShipController from installed template (generate-controller) 

Also
```
grails create-controller Ship  --- works

grails generate-controller Ship --- gives error:
| Error Domain class not found for name Ship.
```
grails generate-controller scaffolder.Ship is required in this case.

**Comment by graemerocher** [comment]
Only the views are used, Grails 3.x no longer generates a controller at runtime due to the startup cost.

**Comment by hakanernam** [comment]
@graemerocher  From your comment
https://github.com/grails/grails-core/issues/681#issuecomment-125300546

I assumed old functionality was reinstated. Static generation is alright, but still, in a newly generated application, Dynamic scaffolding seems to be working:

```
class Car {
    String brand
    static constraints = {
      brand blank:false
    }
}

class CarController {
   static scaffold = Car
}
```
A car is saved and shown.

![screenshot at sep 11 16-13-48](https://cloud.githubusercontent.com/assets/1321157/9815741/0829ef9e-58a1-11e5-83b1-beaed7465c58.png)

**Comment by graemerocher** [comment]
Right, in previous versions of the scaffolding plugin we took the `Controller.groovy` template and dynamically compiled it. This had a number of problems (startup time, unpredictable permgen usage, volatility etc.). The new version of the plugin in 3.x uses AST transformations to create the scaffolded controller and does not use the template. So yes this small piece of functionality has been lost, but frankly it wasn't worth it for the hassle.

**Comment by hakanernam** [comment]
Ok,  makes sense now, thanks.

**Comment by bitsnaps** [comment]
@graemerocher any workaround to replace a generic default `Controller.groovy` in scaffolding?
