### ISSUE TITLE
Add lifecycle event for new Hibernate session factory

### ISSUE THREAD

**Issue by pledbrook** [grails/grails-core#9160]
Grails 3 currently supports the reloading of domain classes, but in doing so it recreates the session factory (or so it seems). The result of this if you're using `create-drop` is that you lose all your data. Since the `BootStrap.init` is not executed again, one is forced to restart.

One workaround is to specify `update`, but a developer may not want the data generated during a development session to be retained between server restarts. Plus `update` can leave dud columns around.

I think the ideal solution is to add an event to the application lifecycle that triggers when the session factory is recreated. Developers can then move their initial data from `BootStrap` to an event handler.

**Comment by olavgg** [comment]
I think this is a great idea! I have the same problem, and find this frustrating.

**Comment by graemerocher** [comment]
I've added an event that gets fired on the GORM side:

https://github.com/grails/grails-data-mapping/commit/5207c5106f9812e3fb96aed4289d0f5497fa3698

Now just need to update the Grails side to listen for side event and profile a generic lifecycle hook

**Comment by graemerocher** [comment]
With this commit GORM events are translated into Reactor events. So now any GORM event can be listened for:

https://github.com/grails/grails-core/commit/baac8afcf73a5f7efaef4ea562276287a1de02e4

To get what you are after you would need a event consumer that listened for the DatastoreInitialized event:

	@Component
	@Consumer
	class DataSetup {
		
		@Selector('gorm:datastoreInitialized')
		@Transactional
		void init() {
			// do setup work here
		}
	}

It is hard to translate this into a generic lifecycle hook because Grails core is not dependent on Reactor or GORM/Hibernate. So I'm not sure yet how to fulfil that final requirement.

**Comment by pledbrook** [comment]
The fact that Grails core isn't dependent on  either of those two implies this shouldn't be a lifecycle event. This solves the problem, fits with what looks like the new standard Grails event model (it's only a little lower level than the old lifecycle events), and seems fairly easy to set up. The only thing potentially missing is some documentation (I haven't checked that yet). Otherwise, I consider the issue done.

**Comment by graemerocher** [comment]
Thanks for the feedback, closing...
