### ISSUE TITLE
Grails 2.5.1 Criteria projection "count" does not work in Mocked Domain in Hibernate 3 Unit Test 

### ISSUE THREAD

**Issue by boardbloke** [grails/grails-core#9173]
The method count is not implemented.

If you change the test so that the projection uses countDistinct then it works.

See project at https://github.com/boardbloke/grails-9173

**Comment by jeffbrown** [comment]
I sent a PR to your project showing 1 way that you can unit test that criteria.  While looking at that I noticed that you are using Hibernate 3 (https://github.com/boardbloke/grails-9173/blob/72d7b0f2ff9178d27034e00dda1d727962d49209/grails-app/conf/BuildConfig.groovy#L69) but using the Hibernate 4 region factory (https://github.com/boardbloke/grails-9173/blob/72d7b0f2ff9178d27034e00dda1d727962d49209/grails-app/conf/DataSource.groovy#L12).  Is that intentional?

**Comment by jeffbrown** [comment]
The PR that I sent demonstrates how you can unit test this with Hibernate.  That should work.

I think the issue here is that `TestCriteriaBuilder` (https://github.com/grails/grails-data-mapping/blob/b7e9ea24eb5411007e3bf632fbe55823701c9b8f/grails-datastore-gorm/src/main/groovy/grails/gorm/TestCriteriaBuilder.java) extends `CriteriaBuilder` (https://github.com/grails/grails-data-mapping/blob/b7e9ea24eb5411007e3bf632fbe55823701c9b8f/grails-datastore-gorm/src/main/groovy/grails/gorm/CriteriaBuilder.java) which does not define a `count(String)` method.  `AbstractHibernateCriteriaBuilder` does provide a `count(String)` method at https://github.com/grails/grails-data-mapping/blob/b7e9ea24eb5411007e3bf632fbe55823701c9b8f/grails-datastore-gorm-hibernate-core/src/main/groovy/org/grails/orm/hibernate/query/AbstractHibernateCriteriaBuilder.java#L368.

I am not sure how complicated it would be to implement `count(String)` for the in memory GORM but that should be a feature request over at https://github.com/grails/grails-data-mapping/issues.

Thanks for the feedback.

**Comment by Jonniosaurus** [comment]
accepting that this is only a workaround: you can avoid the count method and test the rest of your criteria logic with the following in your spock class (for example, assuming it's a testFor(SomeService))

`service.metaClass.count = { String val -> null }`
