### ISSUE TITLE
grails 2.5.1 ignores Spock functional tests

### ISSUE THREAD

**Issue by woezelmann** [grails/grails-core#9236]
I just migrated an application from grails 2.2.4 to grails 2.5.1. Now spock tests are not executed. The test directory looks as following:

    test
       - unit
          - FirstSpec
          - SecondSpec
          - ... (more Spock tests)  
       - functional
          - FirstTests
          - FirstSpec
          - ... (more JUnit & Spock tests)

Following behavior occurs:

    grails test-app unit:spock

> does not run any test

    grails test-app unit:
> runs all spock unit tests

    grails test-app functional:spock
> does not run any tests

    grails test-app functional:
> runs only JUnit functional tests 

With grails 2.2.4 all test have been executed. I followed the migration guide provided at the grails homepage (removing spock-plugin etc.)

**Comment by felipecao** [comment]
Is there a workaround for this? it seems like code-coverage plugin won't generate statistics unless we use test-app unit:spock (http://stackoverflow.com/questions/4679577/does-the-coverage-plugin-cobertura-under-the-hood-report-on-spock-specificatio), but, as per this bug, unit:spock does not work, blocking coverage stats from being generated.

**Comment by graemerocher** [comment]
So by default there is no `functional` test phase unless you install a plugin that supports running functional tests. So that is the reason why `grails test-app functional:spock` does not run anything....

If you want to run functional tests that are spock tests you need to install a functional test plugin (geb for example): http://grails.org/plugin/geb

This will enable the `functional:` phase and allow you to run functional tests. Let me know if this helps?

**Comment by graemerocher** [comment]
Also note that there is no `spock` type anymore as spock is not built in, so with the `geb` plugin installed I would expect `grails test-app functional:` to work but not `grails test-app functional:spock`

**Comment by woezelmann** [comment]
I could solve the problem by using this plug-in: https://grails.org/plugin/functional-spock
