### ISSUE TITLE
namedQueries inheritance in Domain models does not function properly

### ISSUE THREAD

**Issue by pstastny** [grails/grails-core#9260]
Still observing issue https://jira.grails.org/browse/GRAILS-10468 reported on JIRA by Matt Feury. Named queries accessed as properties work OK, but when query is accessed as method it behaves as described by Matt (propertyMissing vs. methodMissing ?). (Grails 2.5.1)

**Comment by graemerocher** [comment]
Named queries are no longer recommended an `where` queries are the replacement

**Comment by daptordarattler** [comment]
You know you guys say namequeries shouldn't be used and where queries are the replacement, yet I don't see any documentation that allows for where queries to be used with custom criteria names in a static context. An example will really help to smoothen the curve.

**Comment by daptordarattler** [comment]
Just combed the documentation and found the implementation

```
import grails.gorm.*

class Person {
    static DetachedCriteria<Person> simpsons = where {
         lastName == "Simpson"
    }
    ...
}
...
Person.simpsons.each { Person p ->
    println p.firstname
}
```

**Comment by daptordarattler** [comment]
While trying to figure this out, I noticed the where method doesn't take arguments. Any solutions? @graemerocher

**Comment by daptordarattler** [comment]
Any update or info on this?

**Comment by brandonlenz** [comment]
@daptordarattler in older versions of grails (2.5.3) it was possible to do the following:

```groovy
class AbstractClass {
    static superNamedQueries = {
        ...
    }
}
```

```groovy
class SubClass extends AbstractClass {
    static namedQueries = {
        AbstractClass.superNamedQueries.rehydrate(delegate, owner, thisObject).call()
        ...
    }
}
```

This however no longer works in grails 3+. It seems that the way named queries are compiled now prevents the rehydrated queries from attaching to the subclasses.

That's why I'm here as well (found this thread via https://github.com/grails/grails-core/issues/11281)

**Comment by brandonlenz** [comment]
I didn't have any luck with replacing named queries with where queries. Where queries cannot be defined parameters unless enclosing them into a method, however doing so statically on the class level to mimic the named query API prevents them from being able to be chained.

That looks like it will have to be a major refactor at some point for us since we use chained namedqueries quite frequently.
