### ISSUE TITLE
application.groovy not loaded on startup with fat JAR deployment

### ISSUE THREAD

**Issue by pledbrook** [grails/grails-core#9270]
I think this is related to issue #9189, particularly as I'm not seeing the problem with Grails 3.0.4, only 3.0.5-7. I have both an application.groovy and application.yml file in grails-app/conf, which work fine with `grails run-app`. But when I package and deploy the app as a fat JAR, the application.groovy files stops being loaded.

I think we need to revisit the discussion in #9189 and start looking at either limiting what the user can do or manually merging all the configuration files in Grails and make that available through the `config` object.

**Comment by graemerocher** [comment]
Yeah the current situation is less than ideal

**Comment by graemerocher** [comment]
@pledbrook When https://travis-ci.org/grails/grails-core/builds/81533718 completes please could you update `grailsVersion` in `gradle.properties` to `3.0.8.BUILD-SNAPSHOT` and confirm it resolves the issue for you.

**Comment by pledbrook** [comment]
Yes, that seems to fix the loading of application.groovy in the fat JAR and the requirement to have an application.yml alongside every application.groovy file. Thanks.

**Comment by graemerocher** [comment]
@pledbrook To explain the change, I have reverted so that the loading behaviour is the same in Spring Boot and Grails. The merging is no longer done in `YamlPropertySourceLoader`. However, to make this work I had to change the way Grails creates the `Config` object because with the previous behaviour config in `application.groovy` would override and replace config in `application.yml`.

Hence the change here:

https://github.com/grails/grails-core/commit/c57aec1d3ec1ca1e6a9a1e5c0eb5febd4db6fe47#diff-3ccd29efe47274169e63d72a7fd226efL91

Will instead merge any nested config objects by checking whether the `PropertySource` is a `NavigableMapPropertySource`

I believe this results in the correct behaviour we are after and have written a functional test to verify that:

https://github.com/grails/grails3-functional-tests/commit/8c7cb4f9b7ebcaea2f43930074658d37d7daccdb

**Comment by graemerocher** [comment]
One note is that if you have the same setting in `application.yml` and in `application.groovy` then `application.groovy` wins and overrides `application.yml`. That is to say if you have in `application.yml`:

      foo:
           bar: 1
           baz: 2

And in `application.groovy`:

      foo { baz = 3 } 

The resulting `config` will be `[foo:[bar:1, baz:2]`. We may want to document this.

**Comment by pledbrook** [comment]
Do the formats have a deterministic precedence order (e.g. .groovy > .yml > .properties) that's environment independent?

**Comment by graemerocher** [comment]
@pledbrook good question, it seems the `PropertySourceLoader` instances are loaded using `SpringFactoriesLoader` which supports ordering via the `@Ordered` annotation or interface. I'll see if I can make some changes to ensure consistent ordering
