### ISSUE TITLE
Instances are not added automatically when id(empty) parameter is in gsp - Grails 3.0.8

### ISSUE THREAD

**Issue by marciomunhoz** [grails/grails-core#9329]
That's just a behavior or a issue?

Thanks.

Example:
https://github.com/marciomunhoz/test

**Comment by Schlogen** [comment]
What steps are necessary to duplicate the issue?

**Comment by marciomunhoz** [comment]
1 - checkout and run project
2 - open localhost:8080/
3 - click on AuthorController link
4 - click on "Create new author / books" link
5 - "Create new author / books" form is already filled
6 - click on "Save author & books" button
7 - the instances not created. (view it on author/index or dbconsole)

**Comment by Schlogen** [comment]
I believe this is by design. If you pass an id parameter it will attempt to query a book instead of creating a new one.

**Comment by marciomunhoz** [comment]
Strange, because acoording a documentation:

"The mass property binding mechanism will by default automatically convert all empty Strings to null at binding time."

Tecnically this property also should be null.

**Comment by Schlogen** [comment]
Corrrect, however the id parameter still exists.

**Comment by marciomunhoz** [comment]
I still believe it's a issue:
https://jira.grails.org/browse/GRAILS-10397

Could you tell me where you are basing your opinion?

Tks!

**Comment by Schlogen** [comment]
@jeffbrown Can you tell me what the desired functionality is here? 

Assuming `convertEmptyStringsToNull == true`, if someone includes `[id: ""]` in the request should it attempt to retrieve an instance with the id of `null` or create a new instance? I think the latter makes more sense.

**Comment by jeffbrown** [comment]
> Assuming convertEmptyStringsToNull == true, if someone includes [id: ""] in the request should it attempt to retrieve an instance with the id of null or create a new instance?

`convertEmptyStringsToNull` is only relevant to data binding.  If I am understanding the issue here, it isn't a data binding issue.  Specifically, `convertEmptyStringsToNull` is not involved in the logic that decides whether to create a new instance or to retrieve an instance from the database.

Relevant logic is at https://github.com/grails/grails-core/blob/7bc691cfeb23c1fa11857260155bb955cac796f5/grails-plugin-controllers/src/main/groovy/grails/artefact/Controller.groovy#L382
