### ISSUE TITLE
Grails 3.0.7 & 3.0.8 BLOCKER: Something changed that made it impossible to secure/override REST resource methods

### ISSUE THREAD

**Issue by codeconsole** [grails/grails-core#9343]
Something changed in compile org.grails:grails-core:3.0.6 -> compile "org.grails:grails-core:3.0.7 dependency that made it impossible to secure REST resource urls using the Spring Security Plugin:

https://github.com/grails-plugins/grails-spring-security-core/issues/385

A simple example application that demonstrates the problem can be found here:
https://github.com/codeconsole/grails3bugs

I am assuming this is a Grails bug and not related to Spring Security because it worked fine in all other versions of grails before 3.0.7 (Versions 3.0.6 and before work fine).

This seems to only be related to REST resource urls.  It may be that REST resource urls might now be completely ignoring the controller.

**Comment by codeconsole** [comment]
Ok, I just confirmed that resources UrlMappings in Grails >= 3.0.7 completely ignore the underlying controller.

This is a MAJOR BLOCKER for me.

Before 3.0.7, all resource methods would call the underlying controller method.

E.g.

The following URLMappings

        "/cars"(resources: "car")

with the following Controller

    CarController {
        def index() { super.index() } 
    }

/cars/index would call the index() method on the CarController.  Now it does not.  This makes it impossible to secure or override the underlying rest methods,

**Comment by graemerocher** [comment]
The issue here is with using dots in the keys, which translates into nesting which then the Spring Security plugin parsing logic is not handling. 

Really the plugin needs updating to the newer configuration API as it will run into these issues as it is still using `ConfigObject` and the older API with manual merging etc.

You can workaround this issue by not using dots in your staticRules. So instead of:

     '/cars.*':          ['permitAll']	

use

     '/cars*':          ['permitAll']	

But the underlying problem will need to be fixed in the plugin.
