### ISSUE TITLE
Databinding: Could the default be to ignore the difference for locale settings for values with dot or comma when mapping to the Double type?

### ISSUE THREAD

**Issue by olavgg** [grails/grails-core#9379]
I know this could be discussed forever in north, west, east and south directions. I usually use the Norwegian locale and we use commas. However when I write a number in a web form, I don't really care if there is a dot or a comma. 101,11 is for me the same as 101.11

Having a default that didn't care if you submitted with comma or dot, would remove code that I feel is just redundant.

How do other people with different locales feel about this? There are probably some edge cases, but I guess they are rare?  Or do users expect to submit form with a 1.234,89 value?

**Comment by graemerocher** [comment]
This is written like a question, is there a bug repot in here?

**Comment by olavgg** [comment]
It's a suggestion.

I just wonder if the default for data binding should be convert a decimal value to a Double while ignoring locale settings. Because right now, if I submit the number 101.11 (with the norwegian locale) to a Command Object with a Double property I get a null value.

**Comment by jeffbrown** [comment]
I am not sure what it would mean for the data binder to ignore the locale.  When the binder converts something like `3,145` to a number, comprehending the locale is required.  In some locales that will be the number three thousand one hundred and forty five and in other locales that will be the number three point one four five.  What is it that you are proposing happen when a String like that is converted to a  number?

**Comment by olavgg** [comment]
I see, changing this would probably create a mess for other people. I guess I will handle this manually for my use case then.

**Comment by jeffbrown** [comment]
@olavgg The data binding plugin provided by core adds beans with names like `defaultGrailsFloatConverter` and `defaultGrailsDoubleConverter` which are instances of `org.grails.databinding.converters.web.LocaleAwareNumberConverter`.  If you want to plug in your own converters that behave however you want, write a class which implements `org.grails.databinding.converters.ValueConverter` and register an instance or instances of that class as beans in the application context for each of the types that you want to customize binding for.  If you do that, the default data binding mechanism will use your converter(s) instead of the default ones.

**Comment by olavgg** [comment]
Thank you for your kind suggestion Jeff. I will look into that.

**Comment by AleksanderGrzybowski** [comment]
Oh crap, just bumped into this today. I understand it is a feature, and it makes some sense, but why fall back to server locale if one is not specified in the web request? Why should an app work differently based on the language of the system it happens to be running on?
