### ISSUE TITLE
Body parameters in PUT-Request with GET Parameter and Body not passing

### ISSUE THREAD

**Issue by cedWetzel** [grails/grails-core#9509]
Similar to https://github.com/grails/grails-core/issues/9106 I want to make a PUT call like

```
curl -X PUT -d 'firstname=Peter&lastname=Pan' http://localhost:8080/user?token=test
```
When I debug and have a look inside the params object I only get the token=test parameter and not my body firstname=Peter&lastname=Pan.
```
[token:test, controller:user, format:null]
```

When I do a POST-Request all parameters pass:
```
curl -X POST -d 'firstname=Peter&lastname=Pan' http://localhost:8080/user?token=test
```
```
[token:test, firstname:Peter, lastname:Pan, controller:user, format:null]
```
By removing the ?token=test parameter, it works fine:
```
curl -X PUT -d 'firstname=Peter&lastname=Pan' http://localhost:8080/user
```

```
[firstname:Peter, lastname:Pan, controller:user, format:null]
```

You can find my example project here:
https://github.com/cedWetzel/PUT-Example

**Comment by jeffbrown** [comment]
I think what you are describing is expected intended behavior.  The body of the request and the request parameters are 2 different things.

**Comment by orubel** [comment]
@cedwetzel If you can wait, I'll be releasing the api-framework plugin soon and this takes into consideration this behavior; this is the same as sending form data with a POST but URL encoding additional data for routing which is not associated with the form data.The GET is SAFE while the form data (POST) is UNSAFE but they are ok to send together as long as you dont have more than more than ONE UNSAFE method with your SAFE method.

I actually make use of this behaviour for 'api chaining'.

Will release code soon. Testing with 3.1.0RC1 as we speak.

**Comment by bobbywarner** [comment]
Looks like the framework has specific logic for PUT and PATCH requests that is not present for POST.  For instance, this [line in GrailsParameterMap](https://github.com/grails/grails-core/blob/master/grails-web-common/src/main/groovy/grails/web/servlet/mvc/GrailsParameterMap.java#L83) is explicitly checking for PUT and PATCH.

**Comment by orubel** [comment]
Well should work not just for POST but for all. Any UNSAFE method should be able to work with SAFE data/url encoded data.

**Comment by bobbywarner** [comment]
@orubel I was going to suggest the opposite.  So, POST would be changed to work like PUT and PATCH.  The reason for this suggestion is because I don't think url params and request body should both be put into the same object (i.e. params) as there could be two variables with the same name.

You can achieve the desired output in the example above by using a different content type for the body. For instance, if the curl command is changed to this:
```
curl -X PUT -H "Content-Type:application/json" -d '{ "firstname": "Peter", "lastname": "Pan" }' http://localhost:8080/api/v1/user?token=abc
```
You can access the JSON data (i.e. firstname and lastname) with `request.JSON` and the url parameters (i.e. token) with `params`.

**Comment by orubel** [comment]
Thats easy to fix. first off, the onus is on the developer but if they do that, you separate your variables by how they are sent: GET variables and POST variables (not talking REST methods... talking GET/POST, Cookie, session, etc). Then do the comparison and throw an error.

This is how I catch that issue.

**Comment by orubel** [comment]
Also, once you start separating you api functionality (ie regular calls, batching, chaining, metrics/reporting, etc), this better establishes a procedure of 'namespacing' variables when they are sent.

**Comment by orubel** [comment]
One other reason I would say don't use PATCH is because that's not what PATCH is for and you're changing the purpose of PATCH to incorporate this. There's no reason to do that really.

**Comment by orubel** [comment]
oh I forgot. I also get past this through abstraction as well. By storing IO State in a reloadable doc which associates URI with expected ROLES/input/output/request method/etc, the backend always knows if an overlap has occurred and resolves in favor of the request method rather than the url encoded data.
