### ISSUE TITLE
Odd behavior with Jar

### ISSUE THREAD

**Issue by bobbywarner** [grails/grails-core#9582]
I am seeing some odd behavior between Grails 3.0.11 and 3.0.12.  In particular, the odd behavior seems to happen when running the app in production as a fat-jar.  Everything seems fine when running the war though.  Did something change related to this?

```
grails create-app urlmappings
cd urlmappings/
grails create-controller foobar
```
vi grails-app/controllers/urlmappings/FoobarController.groovy
```
package urlmappings
class FoobarController {
    def index() {
        render 'foobar'
    }
}
```

vi grails-app/controllers/UrlMappings.groovy 
```
class UrlMappings {

    static mappings = {
        "/"(controller: "foobar", action: "index")
    }
}
```

This works find and renders "foobar"
```
./gradlew bootRun
view http://localhost:8080 in browser
```
This does NOT work and throws an error
```
./gradlew assemble
java -jar build/libs/urlmappings-0.1.jar
view http://localhost:8080 in browser
```
Running the War as a Jar does work though and renders "foobar"
```
java -jar build/libs/urlmappings-0.1.war
view http://localhost:8080 in browser
```

Any thoughts why running the assembled Jar no longer works with 3.0.12 (but running the assembled War does work)?

**Comment by graemerocher** [comment]
This is probably due to the changes we made to improve startup time. A large amount of time was consumed scanning the classpath for classes and in order to  improve that we limited classpath scanning to only application classes. This may not be working as expected for JAR files, which is an issue.

However, you can probably work around this in your application by modifying your `Application` class and adding the following method:

    @Override
    protected boolean limitScanningToApplication() {
        return false
    }
