### ISSUE TITLE
Plugin is not able to override gsp from other plugin

### ISSUE THREAD

**Issue by rlovtangen** [grails/grails-core#9689]
Plugin A depends on plugin B and is configured to load after plugin B.
Plugin B has a gsp, e.g. login/auth.gsp. Plugin A defines the same gsp.
Expects to see gsp from plugin A, but the original from plugin B is used.

In Grails 2.5, gsp from plugin A is used.

See example at https://github.com/rlovtangen/grails-override-gsp-example where myplugin depends on spring-security-core and tries to override login/auth.gsp but is unable to.
Switch to branch `overrideInApp` and you get a login/auth.gsp in myapp, this time it overrides the one from spring-security-core.

Grails 3.1.1

**Comment by sdelamo** [comment]
I think this issue is still open. 

I have[ uploaded a repository](https://github.com/sdelamo/gspresolution) which illustrates the problem in Grails 3.2.8.

Given a multi-project build with Grails 3.
With an app which depends on a plugin where the plugin depends on Spring Security core.

If the app overrides a GSP, the app's GSP is used. As illustrated here: 

![img_2249](https://cloud.githubusercontent.com/assets/864788/24321992/257b415a-115b-11e7-884f-51374fb894fc.JPG)

If the app does not define the GSP  I get Spring Security Core login/auth.gsp rendered. I expected the plugin GSP to be used. 

![img_8364](https://cloud.githubusercontent.com/assets/864788/24321994/3db27d6a-115b-11e7-95de-85b33f2fd889.JPG)

**Comment by jameskleeh** [comment]
@sdelamo Your plugin does not define the load order

**Comment by sdelamo** [comment]
Thanks @jameskleeh  

Indeed, adding 

`
    List loadAfter = ['springSecurityCore']
`

In the plugin description solves the issue.
