### ISSUE TITLE
Different war file is created using Grails and Gadle war

### ISSUE THREAD

**Issue by arjangch** [grails/grails-core#9719]
If you use "grails war" and "gradle war" the war file generated are different. Gradle create smaller, 10MB, war file. Gradle war is missing 
- "org.springframework.boot.loader.*"

The other difference is "java -jar grailswar" works and starts internal tomcat. Even though i specifically said "provided" in build.gradle. But "java -jar gradlewar" will NOT work.

| Grails Version: 3.1.1
| Groovy Version: 2.4.5
| JVM Version: 1.8.0_72

**Comment by zyro23** [comment]
i think you might want to call `gradle assemble` instead of just `gradle war`.
`assemble` has the dependency on `bootRepackage` which does exactly what you are missing: https://github.com/spring-projects/spring-boot/blob/master/spring-boot-tools/spring-boot-gradle-plugin/src/main/java/org/springframework/boot/gradle/repackage/RepackagePluginFeatures.java#L95

**Comment by graemerocher** [comment]
There is no `grails war` command anymore really. It is currently defined as a synonym of `grails assemble`. See https://github.com/grails/grails-profile-repository/blob/master/profiles/base/commands/assemble.groovy#L3

We have added it there as a synonym for backwards compatibility but you should use `grails assemble` going forward. The `assemble` task calls `bootRepackage` and is therefore designed around ensuring the WAR file can be executed as runnable WAR (using `java -jar foo.war`) or deployed to Tomcat.

If you don't want the runnable WAR aspects including you can just run `gradle war` as you have encountered.

**Comment by arjangch** [comment]
Oh! So documentation is behind. 
http://grails.github.io/grails-doc/latest/guide/single.html
Thanks
