### ISSUE TITLE
Publish-plugin no longer support --repository option

### ISSUE THREAD

**Issue by marcDeSantis** [grails/grails-core#9732]
There is no documentation for Grails 3.1.1 that explains how to publish a plugin to a local repository like Nexus. Older documentation mentions using `grails publish-plugin --repository=<repo>`, but that results in:
```
Problem with provided build arguments: [-repository]. 
Unknown command-line option '-r'.
```

**Comment by droggo** [comment]
Grails 3 is based on Gradle so I suggest you to refer to Gradle documentation.

By default you should have `gradle installToMavenLocal` task available. You can list all available tasks using `gradle tasks` command.

We use Artifactory and there is plugin for it which works without issues. Probably Nexus has it's own plugins, and you should search for `nexus gradle` to check that.

Also, because Grails plugins are stored on Bintray, there is default support for it.

**Comment by graemerocher** [comment]
As mentioned above, this is not a bug, Gradle is now used for publishing, you merely have to configure Gradle appropriately.

**Comment by marcDeSantis** [comment]
It isn't a bug, but it's definitely unclear based on the documentation as it stands. Latest makes no mention of publishing to a custom repo, and [docs for 3.0.0](http://grails-plugins.github.io/grails-release/docs/manual/guide/plugins.html) do not work in 3.1.1

**Comment by graemerocher** [comment]
Those docs are for version 3.0.0 of the release plugin for Grails 2. Nevertheless fair comments, please feel to contribute to https://github.com/grails/grails-doc/blob/master/src/en/guide/plugins/repositories.gdoc to improve the documentation in this area.
