### ISSUE TITLE
do not make every Jar task depend on assetCompile

### ISSUE THREAD

**Issue by zyro23** [grails/grails-core#9815]
* https://github.com/grails/grails-core/blob/master/grails-gradle-plugin/src/main/groovy/org/grails/gradle/plugin/core/GrailsGradlePlugin.groovy#L302
* https://github.com/bertramdev/asset-pipeline/blob/master/asset-pipeline-gradle/src/main/groovy/asset/pipeline/gradle/AssetPipelinePlugin.groovy#L86

currently, every `Jar` task gets a `dependsOn assetCompile` - from the looks both in `grails-gradle-plugin` and `asset-pipeline`.

imho, this should be configurable and default only to the applications main artefact.

the current behavior is problematic when building any additional custom jar and so also when using `pathingJar = true` because that makes `bootRun` depend on `assetCompile` which seriously slows down app start (the more assets, the slower ofc..).

at the moment, i am using `gradlew bootRun -x assetCompile` for development.

with the current behavior, another issue is that if not excluded manually, the `assetCompile` output is also copied into every custom jar by default, which is completely undesired.

ref. https://github.com/bertramdev/asset-pipeline/issues/76

**Comment by flofreud** [comment]
Due to `assetCompile` the pathingJar contains the assets and the asset pipeline manifest. When grails is executed in devMode, the asset-pipeline will serve the generated assets instead of the files on system => no reloading.

As workaroung the manifest can be unset in the Bootstrap.groovy:

```
if (Environment.isDevelopmentMode()) {
      // reloading issue cause by asset compilation on pathing jar generation for windows
      asset.pipeline.AssetPipelineConfigHolder.manifest = null
}
```

I hope this information might help someone.

**Comment by graemerocher** [comment]
I have removed the relevant code from Grails:

https://github.com/grails/grails-core/commit/01796743cd338d0cfb3e2ce38d7471f9c87d3a91

Since this is essentially duplicated by the asset pipeline gradle plugin. So to resolve this completely will require a new release of `asset-pipeline`. I will discuss with @davydotcom about doing that.

**Comment by graemerocher** [comment]
Since this requires a new release of asset pipeline to resolve moving to 3.1.6 milestone as @davydotcom  can release an updated version that resolves it even after 3.1.5 is out

**Comment by graemerocher** [comment]
Fixed by upgrade to asset pipeline 3.2

**Comment by zyro23** [comment]
thanks. i think https://github.com/grails/grails-profile-repository/blob/master/profiles/base/features/asset-pipeline/feature.yml#L7 should be updated to 2.8+, too?

**Comment by graemerocher** [comment]
it has been on the 3.1.x branch https://github.com/grails/grails-profile-repository/blob/3.1.x/profiles/base/features/asset-pipeline/feature.yml
