### ISSUE TITLE
3.1.4 - reloading - NoSuchMethodError after adding new method to service

### ISSUE THREAD

**Issue by zyro23** [grails/grails-core#9829]
see referenced sample app.
* run-app
* http://localhost:8080/reloading
 * `MissingMethodException`
 * OK, service method is commented out
* add `ReloadingService.foo` (remove comments)
* http://localhost:8080/reloading
 * `NoSuchMethodError: ReloadingService.__execute([Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/String;)Ljava/lang/Object;`
 * not OK, service method should be available now

no difference if spring proxy or grails `@Transactional` is used, no difference if `grails run-app` or `gradlew bootRun` is used.

**Comment by aclement** [comment]
I'm a bit confused why this is coming up now - hasn't it always been an issue? From what I've learned, it perhaps should have been...

The problem here is that a class is getting processed twice, one of the 'callsite' classes that groovy creates to fast-call some target method (in this case the ReloadingService$foo class).

The first time through every method invocation is replaced with a check to see if the target method is directly callable (this is the `ivicheck`call ) and if not directly callable we invoke `__execute()` which is a special method inserted to handle invocation of all methods that didn't exist on a type when it was first loaded (so it would handle `foo` here). But if this class is processed twice we try to intercept what was inserted earlier, hence you see ivichecks for __execute.  This should not happen.

The reason this is happening because of special handling for the Groovy Callsite classloader. The GroovyPlugin inside SpringLoaded intercepts the defineClass in the callsite loader.  Because the plugin is doing it, we shouldn't do it again later. A basic change we can make is recognize a class that has been treated this way and not process it a second time.

As I write this I wonder if the GroovyPlugin behaviour was deliberately written because these classes previously were not reaching the agent (or were being rejected early) and it was the only way to ensure they were processed. Something may have changed somewhere that is now letting them through the agent and they get this double processing. If that is true then another potential fix could be to remove the GroovyPlugin, but without sufficient testcases in place I'd be nervous to make such a radical change.  I'll work on tidying up the fix and pushing it.

**Comment by graemerocher** [comment]
@aclement It just appeared now because in Grails versions prior to 3.1 we used Spring proxies for service classes that were essentially CGlib proxies. In Grails 3.1 and above we use an AST transformation and removed the cglib proxies. This works great, except for the emergence of this service reloading bug.

I'm not sure why this bug never manifested before, but your first suggestions seems like a reasonable and less high risk fix?

**Comment by aclement** [comment]
my initial proposed fix is pushed, please try out a 1.2.6 snapshot from https://repo.spring.io/webapp/#/artifacts/browse/tree/General/libs-snapshot-local/org/springframework/springloaded/1.2.6.BUILD-SNAPSHOT - I can see a 9-Apr build is already there.

**Comment by graemerocher** [comment]
@aclement the 1.2.6 snapshot works perfectly, a release of 1.2.6 to go into Grails 3.0.16 and 3.1.5 would be great!

**Comment by graemerocher** [comment]
Fixed by the upgrade to Spring Loaded 1.2.6 https://github.com/grails/grails-core/commit/2587826c0fefa3f55984e4390d6534df04a919ee

**Comment by zyro23** [comment]
thanks guys! much appreciated.
