### ISSUE TITLE
Problem With Subqueries

### ISSUE THREAD

**Issue by jeffbrown** [grails/grails-core#9931]
Given a domain class like this:

    class Widget {
        int width
    }

A query like this will fail:

        def results = Widget.where {
            width > avg(width)
        }.list()

The error:

```
ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper - Syntax error in SQL statement "SELECT THIS_.ID AS ID1_0_0_, THIS_.VERSION AS VERSION2_0_0_, THIS_.WIDTH AS WIDTH3_0_0_ FROM WIDGET THIS_ WHERE THIS_.WIDTH > (SELECT  FROM WIDGET THIS_)[*] "; expected "RIGHT, LEFT, FULL, INNER, JOIN, CROSS, NATURAL, ,, SELECT"; SQL statement:
select this_.id as id1_0_0_, this_.version as version2_0_0_, this_.width as width3_0_0_ from widget this_ where this_.width > (select  from widget this_) [42001-191]
```

The project at https://github.com/jeffbrown/avgproblem demonstrates the problem.  That query is executed in `BootStrap` so just starting the app triggers the behavior.

**Comment by jeffbrown** [comment]
I am not 100% sure but this might be peculiar to H2.  At least 1 test indicates that this works as expected with Postgresql.

**Comment by jvesouza** [comment]
It seems that problem also happens when using postgresql.
I tried the following:
		final c = Venda.where {
			total > avg(total)
		}
		.total.bookName

The command above was translated to the following query:
Hibernate: select this_.total as y0_, this_.book_name as y1_ from venda this_ wh
ere this_.total > (select  from venda this_)

I receive the following error:
ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper - ERROR: subquery must re
turn only one column

**Comment by Schlogen** [comment]
This is happening in GORM 6 as well

**Comment by Schlogen** [comment]
Fixed by https://github.com/grails/grails-data-mapping/pull/753
