### ISSUE TITLE
Applying the layout without the layout meta tag for all actions inside a "MainController"

### ISSUE THREAD

**Issue by quindimildev** [grails/grails-core#9940]
Grails is including the layout into a gsp without the layout tag on the gsp head. I have test this into a new grails project with grails 3.0.x and grails 3.1.x
### Steps to Reproduce

1. Create a controller called "MainController" 
2. Create an action inside, for example an "index" action.
3. Create it's gsp in views/main/ -> index.gsp, don't use the layout here, for example an gsp with only body
4. Visit the action on localhost:8080/main/

It happens also with others actions inside the "MainController", I guess is related by convention over configuration.

### Expected Behaviour

Should render only the body content, no more, without any layout

### Actual Behaviour

Inserts the layout main, visually it's rendering the grails header

### Environment Information

- **Operating System**: TODO
- **Grails Version:** 3.0.16 (this happens also in 3.1.x)
- **JDK Version:** java version "1.8.0_66"

**Comment by graemerocher** [comment]
This is by design, if you have a layout named after your controller (in this case `MainController` and `main.gsp`) it will apply it to the controller by convention. If you don't want this to happen either rename your controller, specify an explicit `layout` property in the controller or rename the `main.gsp` layout to something else.
